### ISSUE TITLE
Home --> Job Seeker Registration

### ISSUE THREAD

**Issue by rukku3** [gak112/DearJobTesting#10]
Please create a separate page/section only for Skill Set. The input should be taken in the form of keywords so those specific keywords can be used to create personalized recommended jobs for the jobseeker. 

**Also please add a calendar input next to each skill so we can calculate the experience level for each skill. 

For example, 

Skill                  Experience Level  
AngularJS         6  years                
Python             4  months                

**This should be done in the registration process only.**

**Comment by srinuheroictechno** [comment]
completed
