### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscription History: wrong history

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#106]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscription history

Actual result:
Some incorrect history is displayed

Expected result:
Only my company's history to be displayed

**Comment by eraytech** [comment]
Issue appears for Jobseeker login also. Remove dummy data.

![image](https://user-images.githubusercontent.com/101229315/213578388-54e964e9-a737-4e20-92a7-fa76ef9e347c.png)

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by eraytech** [comment]
![Screenshot 2023-06-02 000837](https://github.com/gak112/DearJobTesting/assets/101229315/71530744-9130-4401-941d-35d5b1f5ce8a)


payment amount column is not visible, neither scroll bar does not exist to see it

**Comment by eraytech** [comment]
Subscriptions displaying multiple times - 

![image](https://github.com/gak112/DearJobTesting/assets/101229315/5d91c5d9-5ec5-494c-99dc-4393117ebace)

**Comment by eraytech** [comment]
Working fine
