### ISSUE TITLE
Web -> Employer Login -> Basic details -> Inbox: New msg doenst go

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#108]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Basic details-> Inbox
4.Click New message and try to send to any valid or invalid email

Actual result:
Nothing happens after 'Send' button is clicked

Expected result:
For valid, email should be sent. And for invalid, error should be displayed

**Comment by Abhinavgunda25** [comment]
Inbox is working ., Please Check

**Comment by Abhinavgunda25** [comment]
![WhatsApp Image 2023-05-05 at 11 08 24 AM](https://user-images.githubusercontent.com/49630766/236385145-406275f5-5d02-456c-a30c-c44f0d293f53.jpeg)
otp has been sent to registered email address

**Comment by eraytech** [comment]
Verified and Closed
