### ISSUE TITLE
Home --> Job Seeker Registration --> Employment Details

### ISSUE THREAD

**Issue by rukku3** [gak112/DearJobTesting#11]
Please add the options "On-Site", "Remote", "Hybrid".

Please change the way the options are selected so 3 options can be selected in this page. 

- One option is b/w "Full Time" and "Part Time"
- One option is b/w "On-Site" "Remote" "Hybrid"
- One option is b/w "Contracts" and "Third Party"

Further changes will be given by Kiran at a later time.

**Comment by srinuheroictechno** [comment]
completed
