### ISSUE TITLE
Web -> Home page - > Without logging IN at all-> 'Reset' Search is not available

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#112]
1.In the landing 'Home page'
2.Try to Search with 'Angular'. This will show some results
3.Now if I change my mind to search for 'Ajax' from this search results. This doesnt show any results

Actual result:
Search results are shown for 'Angular' and this page doenst get a reset if I want to change my search criteria.

Expected result:
It would be good to have a 'Reset/modify' search critirea

**Comment by eraytech** [comment]
retested with above steps and didnt worked as expected.

**Comment by Abhinavgunda25** [comment]
Reset has kept in job search., Please check
![dearjob1](https://user-images.githubusercontent.com/49630766/227699150-3a76edc6-d57f-48d3-a1bb-8a0395eedd4c.PNG)

**Comment by eraytech** [comment]
Verified and Closed
