### ISSUE TITLE
[Web] New registration page text unable to edit

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#125]
1. Go to Home page
2. Click on [Register] menu
3. Under "What type of User are you?", there is text under Job seeker, Employer and Staffing consultancy.

Actual result:
Default text shows

Expected result:
This text shall be editable from Admin page.

![image](https://user-images.githubusercontent.com/101229315/212383972-041e0875-47da-433a-a071-4b2f655ed56e.png)

**Comment by eraytech** [comment]
Details are showing as paragraph. Can we display statements in each separate line as entered from Admin page.

Actual:
![image](https://user-images.githubusercontent.com/101229315/212956815-38a767e3-27da-47f3-adb2-360cd2538eff.png)

Expected:
![image](https://user-images.githubusercontent.com/101229315/212956904-b7601946-75c4-4a62-916f-d5ff2900f43a.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Verified and closed
