### ISSUE TITLE
[Web] Home page: Search job with a skill and it is not added to Skills list in Admin page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#130]
1. Go to DearJob home page.
2. Input "Project Manager" in Job title. Skills text box and click [Search] button.
3. Login to Admin page
4. Go to Masters -> Skills
5. Check for "Project Manager" skill is added to Skills list

Actual result:
Project Manager is not added to skill set.

Expected result:
1. While searching for Skill set in home page, show next words that match from skills list in Admin. (Ex: If jobseeker starts typing "P" show all skills from skills list starts with P (ex: Python, Project Manager etc). Once jobseeker completes typing and if the skill is not available in skill list, add that skill to skills list in Admin.

![image](https://user-images.githubusercontent.com/101229315/212429771-6cf32db8-250e-434d-a05e-7d63e388744e.png)

Project Manager shall be added to this list.
![image](https://user-images.githubusercontent.com/101229315/212429808-4e7c4888-486e-406b-bd5c-c28ec57b88fc.png)

**Comment by Abhinavgunda25** [comment]
When you enter in Search box and click Search button. The word you enter will save in Admin Panel Skills List

**Comment by eraytech** [comment]
Issue still existing

**Comment by Abhinavgunda25** [comment]
1. Search Word "Data science" in search home page
![t-130](https://user-images.githubusercontent.com/49630766/236385898-5134cea0-8fec-4933-b6c8-a05663f5c6e6.PNG)
2. Data saved in skills as "Data Science" ., Please refresh the search in skills page 
![130-2](https://user-images.githubusercontent.com/49630766/236386064-1053e820-caf1-4f75-b720-c132d0ef7b12.PNG)
in admin panel.

**Comment by eraytech** [comment]
While searching for Skill set in home page, show next words that match from skills list in Admin. (Ex: If jobseeker starts typing "P" show all skills from skills list starts with P (ex: Python, Project Manager etc). Once jobseeker completes typing and if the skill is not available in skill list, add that skill to skills list in Admin.

- it should show like in image 1

image 1
![image](https://user-images.githubusercontent.com/101229315/236633447-9faf0723-448f-4be8-8306-3478793141e9.png)
image 2
![image](https://user-images.githubusercontent.com/101229315/236633488-eab7b27e-6525-416a-b987-bd919462afb2.png)

**Comment by eraytech** [comment]
Raised separate issue#436 for this.
