### ISSUE TITLE
[Web][JobSeeker] State name is showing twice in many job search result tiles

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#137]
1. Search for a job, go to search results
2. Check the location of job

Actual result: In many tiles, State name is showing twice. One time in abbreviation and another time in full name.
Ex: California, CA

Expected result: Shall show full name only: California

![image](https://user-images.githubusercontent.com/101229315/212441989-49f0acb3-6a35-4e29-8d92-f8c510012930.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Issue is resolved
