### ISSUE TITLE
[Web][Jobseeker] Change in tile design for job search results

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#138]
Actual tile:
Hourly word shows next line. 
Yrs word shows next line
Location details shows in 2 lines.

![image](https://user-images.githubusercontent.com/101229315/212442606-508931ee-9217-480b-bf4a-a5ef8b159a21.png)

Expected tile:
In 1st row: Show Salary in 1st half of tile. Experience in 2nd half of tile
In 2nd row: Show location in single line

![image](https://user-images.githubusercontent.com/101229315/212442877-8821a376-b7c9-4105-8b67-018f67a96403.png)

**Comment by eraytech** [comment]
Add "information" icon on top left side of all **imported job** tiles.
When mouse hover to "information" icon, a tool tip shall read, "This job is imported from third party website, You'll be redirected to our partner website to continue apply for the job"

![image](https://user-images.githubusercontent.com/101229315/212942775-cbbf1f96-bf00-40e3-9d81-780f5b968940.png)

**Comment by eraytech** [comment]
When mouse hover to "information" icon, a tool tip shall read, "This job is imported from third party website, You'll be redirected to our partner website to continue apply for the job"

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by eraytech** [comment]
Working as expected, verified.
