### ISSUE TITLE
[Web] Print, Email, Share icons does not work in Interview FAQ page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#145]
Yellow highlighted icons are not functioning 

![image](https://user-images.githubusercontent.com/101229315/212445939-0367ed3c-852b-4755-b671-7200557bda70.png)

**Comment by Abhinavgunda25** [comment]
only share option is working fine

**Comment by eraytech** [comment]
Share icon is generating link to https://dearjob.org/#/ but not to Interview FAQ page.

**Comment by Abhinavgunda25** [comment]
Issue has been resolved in interview faqs view

**Comment by eraytech** [comment]
Issue solved
