### ISSUE TITLE
[Web] Add Print, Email, Share icons on Articles.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#146]
Add Print, Email, Share icons same as Interview FAQ's in Articles are opened

![image](https://user-images.githubusercontent.com/101229315/212446029-6ea380d6-97a7-4eed-ae06-43834dfd60a8.png)

**Comment by Abhinavgunda25** [comment]
only share option is working fine

**Comment by eraytech** [comment]
Share icon is generating link to **https://dearjob.org/#/** but not to article.

![image](https://user-images.githubusercontent.com/101229315/213064813-220fbd75-6c2c-4c28-9581-b005a6958357.png)

**Comment by Abhinavgunda25** [comment]
Issue has been resolved in articles view

**Comment by eraytech** [comment]
Issue is solved
