### ISSUE TITLE
[Web][Jobseeker] Full Job description not showing in application details page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#148]
1. Login as Jobseeker
2. Go to Dashboard
3. Go to 'Job application Status' section
4. CLick on "View All"
5. Click on any job title
6. Observe "Application Details" page

Actual result:
Full job description and other details are not showing except for job title, company name and activity on job

Expected result:
1) Shall show full Job details
2) At bottom of page: Show new section:
SIMILAR JOBS
<Show 5 similar jobs>

![image](https://user-images.githubusercontent.com/101229315/212797005-75712667-f448-4d0f-a86d-ba37d737fb68.png)

**Comment by Abhinavgunda25** [comment]
issue has been resolved

**Comment by eraytech** [comment]
Verified and closed
