### ISSUE TITLE
[Web][Jobseeker] Change "View All" link to "Subscribe" button in priority applicant tile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#149]
1. Login as Jobseeker
2. Go to Dashboard
3. Observe "priority applicant" panel on right side

Actual result:
Shows "VIEW ALL" link directs to subscription page

Expected result:
Change "View All" link to [Subscribe] button. This panel shall show only to non-subscribed jobseekers only

![image](https://user-images.githubusercontent.com/101229315/212797955-05ac2c86-4fe5-4ee2-b87a-9962b8a19d6f.png)

**Comment by eraytech** [comment]
Change spelling to: **SUBSCRIBE**

**Comment by eraytech** [comment]
Spelling mistake happened : Subscibe instead of  SUBSCRIBE

**Comment by Abhinavgunda25** [comment]
issue has been resolved

**Comment by eraytech** [comment]
Verified and closed
