### ISSUE TITLE
[Web][Jobseeker] Not allowing to upload word/pdf as resume

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#151]
1. Login as Jobseeker
2. Go to Edit Profile
3. Click on "+Add Resume" link in "Upload Resume" section
4. Observe popup

Actual result:
Shows supported format as jpg, png, gif etc. When clicked on [Choose file] it does not allow to select word doc, pdf resume (These are general formats for resumes)

Expected result:
Shall show supported format as .doc, .docx, .pdf, .rtf etc and shall be able to upload these formats resumes

![image](https://user-images.githubusercontent.com/101229315/212801515-52de2043-f95b-4fe4-b3c6-0a264b324323.png)

**Comment by eraytech** [comment]
Now able to upload profiles: word and pdf.
Even when word doc is uploaded, icon shows as pdf. It shall show word doc icon.

![image](https://user-images.githubusercontent.com/101229315/212941400-75ef03fa-be9d-4c1f-b3ff-fa03182ef702.png)

**Comment by eraytech** [comment]
Same issue at [Add my Resume] page
Supporting formats shall be updated and allow to select word/pdf/rtf files..

![image](https://user-images.githubusercontent.com/101229315/212946772-fe54b40f-1618-4de8-9aa4-7aa3dc4896e8.png)

**Comment by Abhinavgunda25** [comment]
issue has been resolved

**Comment by eraytech** [comment]
Verified and Closed

**Comment by eraytech** [comment]
After clicking [Submit], popup stays in [....] status for long time. Profile not uploading. Tried 2 times.

![image](https://user-images.githubusercontent.com/101229315/213248304-57b8a7d3-9d3a-4691-9eba-5df6ecdaa771.png)

**Comment by eraytech** [comment]
1) Issue: 1 : Able to upload word document, but word icon is not showing and there is no profile

![image](https://user-images.githubusercontent.com/101229315/213352090-3232ac21-f1dc-4ef9-86be-39e638b64bd3.png)

2) Change request:
Change table format design, it looks very old style.

3) Issue 2: When first resume is uploaded, make it default profile. If user uploads another profile and makes it default, turn-off default for 1st profile. At a time, only 1 default profile shall be allowed.

![image](https://user-images.githubusercontent.com/101229315/213352726-57f541a5-5565-46a6-bb27-11b2ed7d3234.png)

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by eraytech** [comment]
Uploading is not working in home> resume> add my resume

![image](https://user-images.githubusercontent.com/101229315/236774598-9683fde0-d467-438f-8537-ddafc43b8c72.png)

**Comment by eraytech** [comment]
'Submit' button not working when tried to submit resume, and for second time clicking on 'submit' shows [...]

![Screenshot93-Submit issue](https://github.com/gak112/DearJobTesting/assets/101229315/00bba8ba-8da4-4214-9ac2-06837be5e1c8)

**Comment by eraytech** [comment]
verified.
