### ISSUE TITLE
[Web][Jobseeker] Resume title accepting over 250 chars

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#152]
1. Login as Jobseeker
2. Go to Edit profile
3. Click on Edit icon on Resume title
4. Pop up displays. Type more than 250 characters in Resume Title text box.

Actual result: 
1) Accepting over 250 chars
2) 250 Characters left text is not updating in real time while typing

Expected result:
1. Shall accept max 250 chars
2. Characters left shall update while typing

![image](https://user-images.githubusercontent.com/101229315/212803163-3961bffb-0a2b-472e-860a-45609c001e00.png)

**Comment by eraytech** [comment]
Verified and closed

**Comment by eraytech** [comment]
Similar issue in "Profile Summary" popup

![image](https://user-images.githubusercontent.com/101229315/213092941-6711a4cb-e5e3-4638-a291-3a0a8712f72c.png)

**Comment by Abhinavgunda25** [comment]
Issue has been resolved

**Comment by eraytech** [comment]
Verified and closed
