### ISSUE TITLE
[Web] [Jobseeker] Mobile should accept numbers not alphabets

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#156]
1. Job seeker Login
2. Click on job seeker
3. Click on edit profile in basic details
4. Click on edit mobile number and submit
Actual result : Mobile number accepting the alphabets
Expected result : Mobile number should accept only numbers

![Screenshot 2023-01-17 185248](https://user-images.githubusercontent.com/101229315/212910464-2d00e75e-1706-44bd-8df2-22190e36bc7a.jpg)
![Screenshot 2023-01-17 185637](https://user-images.githubusercontent.com/101229315/212910849-ab161479-5dfb-4330-94b7-e9cf83db7b37.jpg)

**Comment by Abhinavgunda25** [comment]
Issue has been resolved

**Comment by eraytech** [comment]
Verified and closed
