### ISSUE TITLE
[Web] DearJob name to update in tab, and URL in address bar

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#157]
1. Open browser and go to dearjob.org
2. Observe name on browser tab
3. Observe URL in address bar

Actual result:
2. Name shows as "DearJobWeb"
3. URL shows as "https://dearjob.org/#/"

Expected result:
2. Name shall show as "DearJob"
3. URL shall show as "https://dearjob.org/"

![image](https://user-images.githubusercontent.com/101229315/213065417-89bdc5f5-d2da-439e-b35d-5e00900951b2.png)

**Comment by Abhinavgunda25** [comment]
Name changed to "DearJob" & "#" is important in Tab URL for Project

**Comment by eraytech** [comment]
Verified and Closed
