### ISSUE TITLE
[Web][Admin] Add universities list from backend

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#160]
There are about top 2000 universities in the attached excel sheet.
Please upload them from backend to database.

University list shall appear in Admin->Master->Universities list

[Universities_Top2000.xlsx](https://github.com/gak112/DearJobTesting/files/10442350/Universities_Top2000.xlsx)

**Comment by Abhinavgunda25** [comment]
Universities Added in database ., Please check

**Comment by eraytech** [comment]
Please show all universities in single page or pagination. Currently showing only 1 page data and there is no option to see next data.

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
