### ISSUE TITLE
[Web][Jobseeker] Issues in "Add Skill" section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#161]
1. Login as Jobseeker
2. Go to Edit Profile -> Skill set section, click on [Add Details] button

Actual result:
1) In experience, 0 is not accepting. If user want to enter experience as 5 years 0 months.
2) In popup, text shows as "Specify details about programming languages (such as Java, Python, C/C++, Oracle, SQL etc), softwares (Microsoft Word, Excel, Tally etc) or any other software related knowledge."

Expected result: 
1. Shall accept 0 also in months.
2. DearJob is not specific to IT skill only. This is for all jobseekers in all industries. Change in wording is needed
"Specify details about your each skill set. If it is IT, then programming languages (such as Java, Python, C/C++, Oracle, SQL etc), softwares (Microsoft Word, Excel, Tally etc) or if it is hospital industry, then nursing, Lab technician etc."

Change: "IT Skills" to "Job Skills"
Change: "Please enter IT Skills" to "Please enter Job Skills"

![image](https://user-images.githubusercontent.com/101229315/213092600-216642f5-4fdf-426c-aa2a-5aeb13c38dbe.png)

**Comment by Abhinavgunda25** [comment]
Issue has been resolved

**Comment by eraytech** [comment]
Verified and Closed
