### ISSUE TITLE
Spelling mistake happened : Subscibe instead of  SUBSCRIBE

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#162]
Spelling mistake : Subscibe instead of  SUBSCRIBE

_Originally posted by @eraytech in https://github.com/gak112/DearJobTesting/issues/149#issuecomment-1386831652_

**Comment by Abhinavgunda25** [comment]
issue has been resolved

**Comment by eraytech** [comment]
Verified and Closed
