### ISSUE TITLE
[Web] [Employer] Only IT Skill set is showing in post a job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#164]
1. Login as Employer
2. Click on employer
3. Click on post a job in job details
4. Scroll down and click on skill set

Actual Result : Only IT Skill set is showing

Expected result : Skillset should accept all type of skills like [ sales, communication, management] 

![Screenshot 2023-01-18 211513](https://user-images.githubusercontent.com/101229315/213221930-3e0cd20d-f72f-4861-8768-ed477a7c8ab6.jpg)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by Abhinavgunda25** [comment]
issue is resolved., Please check

**Comment by eraytech** [comment]
Retested and working as expected. Hence this defect can be closed
