### ISSUE TITLE
[Web] [Employer] '0' zero Should accept in minimum experience

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#165]
1. Login as Employer
2. Click on employer
3 .Click on post a job in job details
4. Scroll down enter minimum experience as zero '0'
5. Fill other details and click on submit

Actual result : Error is showing when we enter '0'

Experience result : Accept the Zero '0' in minimum experience

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Retested and working as expected. Hence this defect can be closed
