### ISSUE TITLE
[Web] [Employer] Payment page is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#167]
1. Login with Employer
2. Click on employer
3. Click on subscriptions in job details 
4. Click on subscribe now button by selecting any plan 
5. Click on payment
Actual result : Proceed to payment button is not working, Removing of promo code is not working
Expected result : Proceed to button and removing of promo code should work , Total payment page should work properly.

![image](https://user-images.githubusercontent.com/101229315/213249434-6b2fd7b8-7a18-4704-88b8-af3b1830d02b.png)

**Comment by Abhinavgunda25** [comment]
Procced to pay & promo code is working fine now., Total Payment page is working

**Comment by eraytech** [comment]
Verified and Closed
