### ISSUE TITLE
[Web][Jobseeker] Page does not go to TOP when clicked on page numbers at bottom

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#168]
1. Login as Jobseeker
2. Search for job (or any pages that has pagination)
3. Scroll down and click on page 2.

Actual result:
Moves to page 2, but page stays at bottom. Page [2] number color changes to white and not visible unless mouse hover.

Expected result:
Move to page 2 and show top of the page.

![image](https://user-images.githubusercontent.com/101229315/213258902-32f1e0ea-2a6f-425f-8bcb-25c5a50fa8ed.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Verified and closed
