### ISSUE TITLE
[Web][Jobseeker] RESET button functionality is not defined in job search results

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#170]
1. Login as Jobseeker
2. Search for job and land in job search results page
3. Click on [Reset] button  - nothing happens
4. Click on any Refine by (Ex: ziprecruiter) - [Clear Refinements] button will appear
5. Click on [Reset] button - nothing happens
6. Click on [Clear refinements] - all filters are cleared.

Actual result:
Looks like [Reset] has no functionality. It can be removed.

![image](https://user-images.githubusercontent.com/101229315/213317863-b57edc9b-8e96-41d6-b498-284d9b5f8aa7.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Verified and closed
