### ISSUE TITLE
[Web][Jobseeker] Unable to select "Full Time" in Career profile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#174]
1. Login as jobseeker
2. Go to Edit profile -> Career Profile -> Click Edit button
3. Career profile popup displays, try to select Full Time

Actual result:
Unable to select Full Time under Employment type.

Expected result:
1) "Desired Job type" and "Desired Employment Type" both are same. 
2) "Desired Job Type" can be removed
3) Under "Desired Employment Type", make all 4 options are check boxes (not radio buttons). Jobseeker may be ready for both Parttime and full time. So he should be able to select multiple employment types.

![image](https://user-images.githubusercontent.com/101229315/213323812-23926fa4-4656-4a99-bced-a1d4fbfa5d06.png)

**Comment by Abhinavgunda25** [comment]
issue has resolved

**Comment by eraytech** [comment]
Verified and closed
