### ISSUE TITLE
[Web][Jobseeker] Pop up does not close after clicking [Submit] in Edit profile page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#175]
1. Login as Jobseeker
2. Go to Edit Profile
3. Click on any edit icon or "+Add xyzz" link 
4. Editable popup or to add new details popup displays
5. Make changes or enter new data and click [Submit]

Actual result:
Data saves and popup still stays

Expected result:
After clicking [Submit[, data shall save and close popup.

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and Closed
