### ISSUE TITLE
[Web][Jobseeker] Unable to edit job title in Edit profile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#176]
1. Login as Jobseeker
2. Go to Edit Profile
3. Try to change Job title under Jobseeker name

Actual result: Unable to edit
Expected: Should be able to edit.

![image](https://user-images.githubusercontent.com/101229315/213325105-7186f9b7-93b7-4db3-9fa3-52b3803d762b.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Verified and closed
