### ISSUE TITLE
[Web][Jobseeker] Imported jobs from "Recommended Jobs" page is not redirecting to third party websites

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#177]
1. Go to Jobseeker Recommended Jobs page
2. Click on any imported job.

Actual result:
Page with header and footer displays with no data

Expected:
Shall redirect to third party website (Ex: to Ziprecruiter or USAJobs website)

**Comment by Abhinavgunda25** [comment]
issue has resolved

**Comment by eraytech** [comment]
Verified and closed
