### ISSUE TITLE
[Web][Jobseeker] Popular Categories paginations are NOT hyperlinked

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#180]
Page numbers are not hyperlinked to go to next pages..

![image](https://user-images.githubusercontent.com/101229315/213358293-30da771d-9399-40e0-8439-f54c59843580.png)

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Verified and closed
