### ISSUE TITLE
Web -> Employer - >  Contact us -> footer links not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#183]
1.Login as employer
2.Goto contact us page
3.Scroll down to footer and try clicking on 'Job seeker' or 'Employer' or 'Staffing consultancy'
4.Scroll further down to copy right description and click on 'Dearjob' link

Actual result:
Links do not work

Expected result:
Should be navigated to respective pages

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Dearjob link in copyright section is not working

![image](https://user-images.githubusercontent.com/101229315/236121712-4514296a-d464-4284-badc-f4137dcfe599.png)

**Comment by Abhinavgunda25** [comment]
dearjob is not linked to any link. It is only display text

**Comment by eraytech** [comment]
Verified and closed
