### ISSUE TITLE
Web -> Employer - >  Interview FAQ's -> Icon links not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#184]
1.Login as employer
2.Goto Interview FAQs page
3.Try to click on either icon or the name like 'JIRA' or its icon,  SAP or SAP icon

Actual result:
Links do not work

Expected result:
Should be navigated to respective pages

**Comment by Abhinavgunda25** [comment]
In Interview FAQ's , For every course we have used view more button , if we click on that button we will go to respective page. we didn't keep any link to name or image, only to the view more button.

**Comment by eraytech** [comment]
Solution 1) Remove hyperlink (hand icon) for entire tile and show only on [View More] button.
Solution 2) When clicked on tile or [View More] button go to respective page.

**Comment by eraytech** [comment]
As described above, solution 1 was applied. Retested and working as expected
