### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions: 'Promo code' can not be removed

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#186]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.select any plan and Click 'Subscribe now'
5.Try to remove promo code

Actual result:
Unable to remove promo code

Expected result:
User should be able remove or change promo code

**Comment by Abhinavgunda25** [comment]
User can change Promo code .,

**Comment by eraytech** [comment]
Able to remove or change promo codes now
