### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions: Unable to add new addresses

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#188]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.select any plan and Click 'Subscribe now'
5.In payment summary page, Click 'edit' icon for billing information
6.Click 'Add Address' and try to submit

Actual result:
Nothing happens here

Expected result:
Addresses should be added

**Comment by Abhinavgunda25** [comment]
Please check., Issue resolved

**Comment by eraytech** [comment]
- After adding the address click on select 
- Selecting the address is not working

![image](https://user-images.githubusercontent.com/101229315/236769815-7a25fda1-dca4-46f4-a12e-4150f4a2430b.png)

**Comment by eraytech** [comment]
a) Remove True False buttons
b) Add Edit, Delete icons
c) Give some gap between radio button and tile
d) Add [Save/Submit] button

![image](https://github.com/gak112/DearJobTesting/assets/101229315/2fb282bc-0f63-4122-b2a6-df955e2664b1)

**Comment by eraytech** [comment]
b) Add Edit, Delete icons 
d) Add [Save/Submit] button
As per the above comments, these 2 are not included.

**Comment by eraytech** [comment]
editing the phone number changing the location field to null/undefined

https://github.com/gak112/DearJobTesting/assets/101229315/3c31ab7f-87de-4613-a4cd-ac230f951a72

**Comment by eraytech** [comment]
showing the total address, without any proper separation of coma and space

![image](https://github.com/gak112/DearJobTesting/assets/101229315/b25aaa3f-ddc3-48ac-8696-c6acd35630aa)

**Comment by eraytech** [comment]
verified and working in andriod 3.3v
