### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions: 'Address' link doesnt work

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#190]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.select any plan and Click 'Subscribe now'
5.In payment summary page, Click 'edit' icon for billing information
6.In 'Address' Page try to click the link 'Subscriptions' in the navigation path on top of page 'Home->Subscriptions->Payment Summary->Address'

Actual result:
It takes you to incorrect subscriptions which is for jobseeker

Expected result:
Should be navigated to Employer related subscription page

**Comment by Abhinavgunda25** [comment]
Please check., Issue resolved

**Comment by eraytech** [comment]
Verified and Closed
