### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions: Unable to add new 'Promo code'

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#191]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.select any plan and Click 'Subscribe now'
5.In payment summary page, try to add new promo code

Actual result:
Nothing happens when a new promo code is added

Expected result:
It should either accept of reject a promo code

**Comment by Abhinavgunda25** [comment]
Please check., Issue resolved

**Comment by eraytech** [comment]
Verified and closed
