### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions: Navigation path is broken

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#192]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.select any plan and Click 'Subscribe now'
5.In payment summary page, verify the navigation path on top of page

Actual result:
It is 'Home->Payment Summary'

Expected result:
It should be 'Home->Subscriptions->Payment Summary'

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
