### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions info is incorrect

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#193]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.verify the plan info displayed

Actual result:
Plan info for Gold , silver & pay per day are incorrect

Expected result:
Price, job posts, profile views and tot users should be correct as per requirement provided

**Comment by Abhinavgunda25** [comment]
As Per Admin Panel ., data will render directly from database. issue resolved.

**Comment by Abhinavgunda25** [comment]
Add/Edit data from admin panel., it reflects to website & mobile app

**Comment by eraytech** [comment]
Verified and closed
