### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions:  Pay per day: no of days is not calculated

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#194]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer

4.Enter start and end dates.

Actual result:
No of days do not reflect

Expected result:
No of days should be reflected as per input selected

**Comment by Abhinavgunda25** [comment]
Pay per day is working now., you can select end date then amount will change accordingly

**Comment by eraytech** [comment]
Verified and closed
