### ISSUE TITLE
Web -> Employer Login -> Job details -> Subscriptions:  Pay per day: Allowed to select past dates

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#195]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Click Employer-> Job details-> Subscriptions
4.Enter past dates for both start and end dates.

Actual result:
It is allowed

Expected result:
Past dates should not be allowed

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Total days count to be corrected, and also price

Actual: 
Start date: 02-May-2023
End date: 08-May-2023
Days count shown: 6 days
Price shown: $30.00

Expected:
Start date: 02-May-2023
End date: 08-May-2023
Days count shown: 7 days
Price shown: $35.00

Days count: 02, 03, 04, 05, 06, 07, 08 = 7 days (include start date and end date also). Posted job shall deactivate automatically on 08-May-2023 11:59 PM EST (or 09-May 12:00 AM EST)

![image](https://user-images.githubusercontent.com/101229315/235777849-2c07bdbd-46ad-4714-acad-ed8e767d7788.png)

**Comment by eraytech** [comment]
Verified and closed
