### ISSUE TITLE
Web -> Employer Login -> Job details -> Posted jobs: Active/Inactive button is not eye catchy

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#197]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Go to Posted jobs and look for status update button

Actual result:
For active job it shows as 'active' and didnt recognised it as a button in first instance

Expected result:
If it is something like an ON/OFF button it would be more user understandable

**Comment by Abhinavgunda25** [comment]
issue is resolved

**Comment by eraytech** [comment]
Retested and working as expected
