### ISSUE TITLE
Web -> Employer Login -> Job details -> Posted jobs: Active/Inactive Status not reflecting

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#198]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Go to Posted jobs and try to make a status update from Active to inactive

Actual result:
A popup messaged is displayed saying status is updated. But the screen doesnt reflect immediately. It reflects only if refresh button is clicked or page is reloaded

Expected result:
Status should be refreshed immediately

**Comment by gak112** [comment]
Not Possible

**Comment by eraytech** [comment]
Active/inactive button is now changed to new on/off button.. will hold the retest activity for few days

**Comment by eraytech** [comment]
As I see status as 'fixed & deployed'. Was anything fixed for above issue..? 

Retested and found that
Deactive to active reflects immediately
But Active to deactive reflects only when screen is refreshed.

Plz confirm on this.

**Comment by Abhinavgunda25** [comment]
Please Do Refresh after updating status

**Comment by Abhinavgunda25** [comment]
Please Do Refresh after updating status.,

**Comment by eraytech** [comment]
Verified and closed
