### ISSUE TITLE
Web -> Employer Login -> Job details -> Posted jobs:Search doesnt work for between letters

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#199]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Go to Posted jobs. If it has a job post 'TEST ENGINEER'

Actual result:
It works for TES or ENG... But it doenst work of EST or GINEER

Expected result:
It would be good if the search is made on any part of a word. Same thing can be applied to all search patterns across the entire application.

**Comment by gak112** [comment]
i think it is not possible, send me if any reference websites..

**Comment by Abhinavgunda25** [comment]
i think it is not possible, send me if any reference websites..
