### ISSUE TITLE
Home page changes

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#2]
1) Slightly reduce font size of "Search your dream job here" in home page 
2) Remove "United States" drop down. This website is only for USA market. Replace with "Location (Zip, City, State)" or similar
3) Change "Font style" for sub headings: "Hiring Companies", "Categories we have", "Jobs on your skill set", "Career articles"
4) Under "Categories we have", change waves style tiles. Waves design won't be recommended for accessibility users.
5) Change Font style in "Jobs on your skill set" tiles for headings. Ex: Angular JS Developer
6) Change background color to Orange in mobile phone app launch.

**Comment by srinuheroictechno** [comment]
done
