### ISSUE TITLE
Web -> Employer Login -> Job details -> Post a job: Max exp lesser than min exp is allowed

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#200]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Go to Post a job.
4. While posting a job give min exp and 6 and max exp as 2

Actual result:
No check and it is allowed. Same with Salary as well.

Expected result:
Max exp should be higher than the min exp

**Comment by gak112** [comment]
issue has been resolved

**Comment by eraytech** [comment]
Retested and this works as expected now
