### ISSUE TITLE
Web -> Employer Login -> Job details -> Post a job: Min and Max salary error is partial

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#201]
1.Register a new employer with basic details only. (ex: Sreedhar & Co LLC)
2.Login as employer
3.Go to Post a job.
4. While posting a job, do not enter salry min or max info

Actual result:
Displayed 'Validation error: Please enter yout minimum'

Expected result:
It should display 'Validation error: Please enter yout minimum Salary'.  Same for Max salary also

**Comment by Abhinavgunda25** [comment]
issue has resolved

**Comment by eraytech** [comment]
Retested and now displays:
Displayed 'Validation error: Please enter your minimum Salary'
or
Displayed 'Validation error: Please enter your maximum Salary'

Hence this defect can be closed
