### ISSUE TITLE
[Web] [Jobseeker] Free Subscribtion also charging the amount in payment page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#202]
1.Login with job seeker
2.Click the Job seeker option
3. Click the subscriptions in search jobs by
4. Click the free subscription 0$/annum 

Actual result : zero '0' dollars is showing 20$ in payment page
Expected result : Pricing is not changing in payment page only it is showing outside of SUBSCRIBE NOW button when we change in admin it should change in payment page

![image](https://user-images.githubusercontent.com/101229315/213452729-eb94fad6-67b6-452b-b621-e38804c7ab6b.png)
![image](https://user-images.githubusercontent.com/101229315/213453400-c64a2633-016a-4362-98d3-6bf2b5ecdd3c.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., Please check

**Comment by eraytech** [comment]
Proceed to pay button is not working for the 0$ payments in [JS/Emp]

**Comment by Abhinavgunda25** [comment]
proceed to pay should not open for $'0' Subscription.

**Comment by eraytech** [comment]
verified
