### ISSUE TITLE
[Web] [Jobseeker] Proceed to pay and Adding of new promo code is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#203]
1.Login with job seeker
2.Click the Job seeker option
3. Click the subscriptions in search jobs by
4. Select any payment Priority/ Free 
5. Click on subscribe now
6. Add new promo code 
7. Click on proceed to pay

Actual result : Promo code Add Button and Proceed to pay Button is not working
Expected result : Promo code Add Button and Proceed to pay Button  should work and Add delete option to remove the copied promo code

![image](https://user-images.githubusercontent.com/101229315/213457302-5c383959-8be5-4ca9-9d64-f5cdeb38f802.png)

**Comment by eraytech** [comment]
- There is no option for delete / remove promo code
- In payment it is showing negative number after applying the promo code

![image](https://user-images.githubusercontent.com/101229315/236379438-9b1d12ad-6fdc-43b5-9522-383c0fd6c514.png)

**Comment by Abhinavgunda25** [comment]
issue reolved., please check

**Comment by eraytech** [comment]
![Screenshot 2023-06-03 033945](https://github.com/gak112/DearJobTesting/assets/101229315/067c12d8-d518-4722-bcff-f8f577e4d380)

The option to remove should be available for the "promo code" and not for the "promo discount"

The "promo discount" should display the discount amount, not the total amount after the discount is applied.

**Comment by eraytech** [comment]
1. Promocode is showing title instead of promocode.
Given
title: Offers
Promocode: Offer2
But, it is displaying Offers(title) instead of Offer2(Promocode) and 
2. Subscription (paid) should be Subscription (plan name)
Eg: For priority subscription, it should show, Subscription(Priority)

![Screenshot111-JS Subscription](https://github.com/gak112/DearJobTesting/assets/101229315/b979299a-7f93-4e92-891a-afa42c5f7871)

**Comment by eraytech** [comment]
Verified and it is working fine.
