### ISSUE TITLE
[Web] [Jobseeker] In Payment Summary  Billing Information Adding, selecting and deleting of address is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#204]
1. Login with job seeker
2. Click the Job seeker option
3. Click the subscriptions in search jobs by
4. Select any payment Priority/ Free
5. Click on subscribe now
6. Click on edit address in billing information
7. Click on add address 

Actual result :  Edit, Add, Select, Delete Address in Billing information is not working
Expected result : Edit, Add, Select, Delete Address in Billing information should work

![image](https://user-images.githubusercontent.com/101229315/213461571-334b2dc0-20e2-4de3-ae24-fe4a30a33931.png)

**Comment by Abhinavgunda25** [comment]
Now., it is Working Fine Please check

**Comment by eraytech** [comment]
House number and street name are not showing in tile. Display House number and street name.

>>Can we change the design of this page - looks very old and too many colors (Blue, Red, Green, Orange).
Suggest to use below design:

Current design (not good):
![image](https://user-images.githubusercontent.com/101229315/235774795-db5ceb1c-6085-4e9c-9528-76ab80c4235e.png)

Proposed design (Same like FAQ's page]:
![image](https://user-images.githubusercontent.com/101229315/235775950-b6f291f2-6fa5-4791-88a0-eff456c49df6.png)

**Comment by eraytech** [comment]
verified, working fine
