### ISSUE TITLE
[Web] [Jobseeker] The Jobs which are posted by Dearjob Employer is not working in jobseeker

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#209]
1. Login with job seeker
2. Click on jobs in demand
3. Select Dearjob in Type section 
4. Click on any job link 
Actual result : Showing page not found when we click the job 
Expected result : The jobs which are posted by dear job employer should work

![image](https://user-images.githubusercontent.com/101229315/213506917-423602ab-a41d-41a0-b831-2aac96a9f9b4.png)

![image](https://user-images.githubusercontent.com/101229315/213507501-2efbcd14-e338-471b-b28e-6ed363223bf6.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and closed
