### ISSUE TITLE
[Web][Jobseeker] "Saved Jobs" Tile design is not same as in "Search results"

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#210]
1. Login as Jobseeker
2. Go to "Saved Jobs"
3. Observe tile design and click on any job

Actual result: 
1) Tile design is not same as in job search result.
2) Job links are not pointing to third party job site for imported jobs

Expected: 
1) Tile design shall be same as in job search result
2) Jobs shall redirect to ziprecruiter/usajobs for imported jobs

![image](https://user-images.githubusercontent.com/101229315/213576949-52c9e3db-7260-4213-a811-7076d3f2132a.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and closed
