### ISSUE TITLE
[Web] [Jobseeker] Reset button is not working in search jobs in demand

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#213]
1. Login with Job seeker
2. Click Jobs in demand > Search jobs by
3. Select few categories
4. Click Reset button

Actual result : Reset button is not working
Expected result : Reset button should work

![image](https://user-images.githubusercontent.com/101229315/213715361-04a334d8-4cf3-4599-afd9-520d2afef9ab.png)

**Comment by eraytech** [comment]
Only it is showing the pop-up message actually Reset button it is not working

![image](https://user-images.githubusercontent.com/101229315/215988634-69744404-7187-47ab-869d-23bf305a7595.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check URL will change when Reset button clicks

**Comment by eraytech** [comment]
It works only when arrived from home page, then reset works.
