### ISSUE TITLE
[web] [Jobseeker] Submit button is not working in add job alert

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#214]
1. Login with Job seeker
2. Click Manage alert display > Basic details
3. Click the Add alert button
4. Fill the details and click the submit button

Actual result : Submit button is not working to add job alert
Expected result : Submit button should work to add job alert

![image](https://user-images.githubusercontent.com/101229315/213722152-2abc3828-10ab-4115-823e-1cb7a4abf2b5.png)

**Comment by eraytech** [comment]
Submit button is not working

![image](https://user-images.githubusercontent.com/101229315/230929772-1414c3d5-d5d0-4877-851a-fab7071fb3fa.png)

**Comment by Abhinavgunda25** [comment]
please check ., issue resolved.,

**Comment by eraytech** [comment]
Verified and closed
