### ISSUE TITLE
[Web] [Jobseeker] Multi apply functionality is missing in saved jobs 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#215]
1. Login with job seeker
2. Click saved jobs > Basic details
3. Select the jobs

Actual result : Multi apply functionality is missing in saved jobs and apply button is also not working
Expected result : Show the Multi apply functionality after selecting a job and apply button should work

![image](https://user-images.githubusercontent.com/101229315/213733541-54554252-6c63-4f9b-a03a-f16213fa7692.png)

![image](https://user-images.githubusercontent.com/101229315/213738845-c9aaf5b8-a28c-4609-860a-b877276c07f6.png)

**Comment by eraytech** [comment]
If these jobs are imported jobs, do not show check boxes. Show only information icon and there should not be [1-Apply] button. 

Check box and [1-Apply] are applicable only for jobs posted directly on DearJob.

**Comment by Abhinavgunda25** [comment]
Issue resolved., Please check

**Comment by eraytech** [comment]
Verified and closed
