### ISSUE TITLE
[Web] [Jobseeker] Refine by functionalities are not working in saved jobs

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#216]
1. Login with job seeker
2. Click the saved jobs > Basic details
3. Click Refine by 
Actual result :  Refine by functionalities are not working 
Expected result :  Refine by functionalities should work in saved jobs

![image](https://user-images.githubusercontent.com/101229315/213736147-264fcd9c-feab-4c66-a650-503bb16fd1ef.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and Closed
