### ISSUE TITLE
[Web] [Jobseeker] Hyperlink is not working in Recommended jobs

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#218]
1. Login with job seeker
2. Click Recommend jobs > Basic details
3. Select next page

Actual result : Hyperlink to select next page is not working
Expected result : Hyperlink  to select next page should work

![image](https://user-images.githubusercontent.com/101229315/213753867-989e5e79-12e4-4d99-9ce5-bcba1103e85a.png)

**Comment by eraytech** [comment]
1. The Refined By functionalities are not working ( When we click the check box it is not accepting )
2. It is not displaying jobs 

![image](https://user-images.githubusercontent.com/101229315/216090936-0f926f61-7f6c-4150-a2b5-c55c83e9900d.png)

**Comment by Abhinavgunda25** [comment]
Issue is resolved., Please check

**Comment by eraytech** [comment]
Verified and closed
