### ISSUE TITLE
Web -> Employer Login -> Basic details -> Inbox: Not able to send email

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#225]
1.Login as employer
2.Go to 'Inbox' and try to send an email

Actual result:
After clicking send button, nothing happens

Expected result:
Email should be sent

![image](https://user-images.githubusercontent.com/101229315/213881067-083f30f2-c020-4ba9-be4c-710713d3334f.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
- Showing different company name,  email id , and once attached photo is displaying in all mails 

![image](https://user-images.githubusercontent.com/101229315/236765121-cf44a0c1-954c-433c-be6c-850a4ead3122.png)

**Comment by eraytech** [comment]
verified
