### ISSUE TITLE
Web -> Employer Login -> Basic details -> Profile Search: download profile is blank

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#226]
1.Login as employer
2.Go to 'Profiles Search'.
3.Select a profile and click on download

Actual result:
Empty html file is downloaded

Expected result:
Employee full profile should be downloaded

**Comment by Abhinavgunda25** [comment]
if you move to download image, if it shows "Download Full Profile" Document will show. if it shows "Does not have resume" user doesn't have resume

**Comment by eraytech** [comment]
Verified and closed
