### ISSUE TITLE
Web -> Employer Login -> Job details -> Application tracking: Cant update status for applicant

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#230]
1.Login as employer
2.In home page just scroll down to all pages
3.Try to shorlist or screen or reject an applicant

Actual result:
Cannot find any buttons to update the applicant status accordingly

Expected result:
Buttons to update the job applicant status is expected

**Comment by Abhinavgunda25** [comment]
In page left side has refine list has applicant status, so from there you can see all job status

**Comment by eraytech** [comment]
not able to add job status, kindly check 

https://github.com/gak112/DearJobTesting/assets/101229315/1aa521d5-1312-4bd4-a230-ced39e8cf3c6

**Comment by eraytech** [comment]
kindly check this:

![image](https://github.com/gak112/DearJobTesting/assets/101229315/3b7e5147-f0f7-44b7-abf4-708413aa3617)

**Comment by eraytech** [comment]
verified and working
