### ISSUE TITLE
Web -> Employer - > Dashboard -> Jobs Activeand their count is not in sync

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#238]
1.Login as Employer and click Dashboard
2.Under 'Job Status', 'total no of jobs active' is shown as '2'
3.But which clicked on 'total no of jobs active', it shows empty list of applicants

Expected result:
'total no of jobs active' count and the actual applicants list should be in sync

**Comment by Abhinavgunda25** [comment]
please check issue resolved.,

**Comment by eraytech** [comment]
Verified and Closed
