### ISSUE TITLE
[Web] [Admin] In Jobseeker option issue with the Expires on and Status button

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#241]
1. Login with Admin
2. Click on Job seeker
3. Click the Status button
4. View the Expires on 
Actual result : Status button is not working and Expires on is not in sync with the database
Expected result : Status button should work properly and Expires on must sync with the database

![image](https://user-images.githubusercontent.com/101229315/215065940-d8e619c2-b938-42d9-b1fb-f80f6a1b6f53.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
verified
