### ISSUE TITLE
[Web] [Admin] In Recruiters the Issue with Contact, Expires on, Status button

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#242]
1. Login with Admin
2. Click on Recruiters
3. Click the Status button
4. View the contact and Expires on
Actual result : Showing hyperlink for email id in contact and status button is not working , Expires on is not in sync with database
Expected result : Remove the hyperlink for email in contact,Status button should work properly and Expires on must sync with the database

![image](https://user-images.githubusercontent.com/101229315/215068594-9d8ea493-a8ea-4c10-ad39-3a487d804817.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
working, verified
