### ISSUE TITLE
[Web] [Admin] In Staffing consultancy Issue with Expires on an Status button

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#243]
1. Login with Admin
2. Click on Staffing consultancy
3. Click on Status button
4. view the Expires on 
Actual result : Issue with Expires on and Status button
Expected result : Resolve the Issue with Expires on and Status button

![image](https://user-images.githubusercontent.com/101229315/215071013-5e093902-3132-408e-9d61-4d0a5c4f1b78.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., expires  on is workign fine.

**Comment by eraytech** [comment]
verified.
