### ISSUE TITLE
[Web] [Admin] In Messages the  Reply button is not working 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#245]
1. Login with Admin
2. Click the Masters > Messages
3. Click the Reply button
Actual result : The Reply button is not working in messages
Expected result : The Reply button should work to give the replies to the messages

![image](https://user-images.githubusercontent.com/101229315/215117622-235ac348-1b22-4777-9187-7dd03c358055.png)

**Comment by eraytech** [comment]
Reply button is not working

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
