### ISSUE TITLE
[Web] [Admin] In Jobseeker Subscription It is showing to Allowed profiles in Add Subscription

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#246]
1. Login with Admin
2. Click the Masters > Job seeker subscription
3. Click the Add Subscription 
Actual result :  In Add subscription it is showing two Allowed profiles instead of Profile viewers
Expected result : Remove one Allowed profile and add Profile viewers instead of two Allowed Profiles

![image](https://user-images.githubusercontent.com/101229315/215123623-d919cbd2-6605-4bec-a510-16764e3ade2b.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Issue still repeating

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by Abhinavgunda25** [comment]
Please Clear cache chrome data & Verify this ticket

**Comment by eraytech** [comment]
verified, working fine
