### ISSUE TITLE
[Web] [Admin] In Users list Submit button of Add user is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#247]
1. Login with Admin
2. Click the Administrator > Users list 
3. Click the Add User
4. Fill the details and click the submit button
Actual result : In Add user the Submit button is not working
Expected result : Submit button should work in Add user option

![image](https://user-images.githubusercontent.com/101229315/215134174-bc67f042-ec19-44cd-9ba7-7537befd1884.png)

**Comment by Abhinavgunda25** [comment]
Issue resolved., Please check

**Comment by eraytech** [comment]
The issue is not resolved

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
- Click the edit button 
- Click the close [X] 
Actual result : Close [X] button is not working
Expected result : Close button should work properly

![image](https://user-images.githubusercontent.com/101229315/236740538-e7d7c0d6-53a1-44a1-9d8c-c8ca64bd3282.png)

**Comment by eraytech** [comment]
'Submit' button is working, but Close [X] button is not working when clicked on 'edit' button.

**Comment by eraytech** [comment]
'Submit' button is working, but Close [X] button is not working when clicked on 'edit' button.

**Comment by eraytech** [comment]
Verified and closed
