### ISSUE TITLE
Web -> Employer Login -> Basic details -> Edit Profile: Email cannot be edited

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#251]
1.Login as employer
2.Goto Edit Profile page and click on edit button
3. Try to update email id.

Actual result:
This field is disabled for updates.

Expected result:
If email updation is restricted, then this field can be hidden in edit page as it is not required. If updation is allowed, then this field should be enabled for editing

**Comment by eraytech** [comment]
Looks like this field is removed from the pop-up editing window. This looks good. But email ID is hidden in the profile page as well now. Due to this user cannot know what email he gave for his profile.  Email Id should be displayed in below red marked area.

![image](https://user-images.githubusercontent.com/101229315/221642376-0f697641-c091-439a-943b-189649d714e9.png)

**Comment by Abhinavgunda25** [comment]
Email can be viewed but can't  be edited

**Comment by eraytech** [comment]
Can you paste a screenshot where email is viewable..???

Im not able to see the email with what I have registered.

**Comment by Abhinavgunda25** [comment]
![dearjob-251](https://user-images.githubusercontent.com/49630766/231782540-a989b927-7088-46b3-a619-4c6d8f1fc89e.PNG)

**Comment by eraytech** [comment]
Verified and Closed
