### ISSUE TITLE
[Web][Jobseeker] Follow button for company does not work

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#253]
1. Login as Jobseeker
2. Search for job and click on company name from search result tile. Company profile page will be displayed
3. Click on [Follow] button

Actual result:
Nothing happens

Expected result:
1) Once clicked, button name shall change to [Following]. If clicked again, shall change to [Follow]
2) If Following, any job posted by the company shall inform Jobseeker through automated email.

![image](https://user-images.githubusercontent.com/101229315/216880270-d8933ebe-d585-4818-8aa8-6a8a082c276b.png)

**Comment by eraytech** [comment]
Issue still repeating

![image](https://user-images.githubusercontent.com/101229315/221911285-d408e319-27ce-4a5e-86be-51e92d76eedb.png)

**Comment by Abhinavgunda25** [comment]
Follow & Following is Done., Please Check

**Comment by eraytech** [comment]
Verified and Closed
