### ISSUE TITLE
[Web][Jobseeker] Company followers count to be updated in realtime

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#254]
1. Login as Jobseeker
2. Search for job and click on company name from search result tile. Company profile page will be displayed
3. Observe the followers for the company under [Follow] button

Actual result:
Number is static

Expected result:
Number should be dymanic and shall update in realtime.

![image](https://user-images.githubusercontent.com/101229315/216880579-e860b9d2-d04c-47c1-a34f-25c39c658692.png)

**Comment by eraytech** [comment]
Issue still repeating

![image](https://user-images.githubusercontent.com/101229315/221913624-e1c1eba5-9f59-441c-b83a-d82afd63bc64.png)

**Comment by Abhinavgunda25** [comment]
Now it is Working Fine., Please Check

**Comment by eraytech** [comment]
Verified and Closed
