### ISSUE TITLE
[Web][Admin] Import (Ziprecruiter) does not work

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#258]
1. Login as Admin
2. Click on Import (Ziprecruiter) and try to import jobs by clicking [Submit]

Actual result:
Nothing happens. Some times button changes to [...] and does not respond

Expected:
Shall import jobs 

![image](https://user-images.githubusercontent.com/101229315/217070765-3742ab7c-a586-4692-94ca-48f9053d832f.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., Please check
