### ISSUE TITLE
[Web][Jobseeker] Free subscription button remove hyperlink and change button name and color

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#259]
1. Login as Jobseeker
2. Menu->Job seeker ->Subscriptions
3. Check subscriptions plans

Actual: Free and Priority both shows [Subscribe now] button.

Expected:
By default, all Jobseekers are "Free" subscribed. So remove hyerlink for [Subscribe Now] button for FREE plan. 
Rename to "Subscribed" and make button color Green background.

![image](https://user-images.githubusercontent.com/101229315/217356765-e96bd464-7dd8-4308-b94f-a9ff41ebad16.png)

**Comment by eraytech** [comment]
Same Issue is repeating

**Comment by Abhinavgunda25** [comment]
Issue Reolved., Please check

**Comment by Abhinavgunda25** [comment]
![dearjob-259](https://user-images.githubusercontent.com/49630766/231778947-5fd59bc4-8ac7-49d8-b5f1-3dc522a4d177.PNG)

**Comment by eraytech** [comment]
Still the issue is not resolved

![image](https://user-images.githubusercontent.com/101229315/235201663-0fa17062-da1c-4f71-b120-26f0b45cfd20.png)

**Comment by eraytech** [comment]
![image](https://github.com/gak112/DearJobTesting/assets/101229315/233eb28a-275c-49d6-a4bb-4e45584d1638)
 still same issue

**Comment by eraytech** [comment]
verified, working fine now.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/3ab227fc-c50d-42c2-a2ed-482ba390ceaa)
