### ISSUE TITLE
[Web] [Staffing Consultancy] In registration it is taking diiferent inputs in password and confirm password

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#264]
1. Click on Register
2. Click on Staffing consultancy
3. Enter the different passwords in password and confirm password

Actual result : It is taking two different inputs password and confirm password
Expected result : It should show the error dialogue box when we enter different inputs in password and confirm password 

![image](https://user-images.githubusercontent.com/101229315/222758054-4f0edf6a-a727-4bdf-bd9f-1dbf44a3f020.png)

**Comment by eraytech** [comment]
Verified and Closed

**Comment by Abhinavgunda25** [comment]
issue Resolved., Please close the ticket
