### ISSUE TITLE
[Web] [Staffing Consultancy] In registration it is not showing any error when we don't fill the complete details 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#266]
1, Click on Register
2. Click on Staffing consultancy
3. Don't fill the below mentioned and click submit button
- Company Name
- Contact Person Name
- Mobile No.
- Company Category
- Company URL
- Full address

Actual result : It is not showing any error message
Expected result : It should show error message " Please fill the details " when we don't fill the complete details 

![image](https://user-images.githubusercontent.com/101229315/222762245-b97744dc-ff4f-414c-9b91-113b919a3cfe.png)

**Comment by Abhinavgunda25** [comment]
Full address is removed., We can view & add in edit profile registration

**Comment by eraytech** [comment]
Verified and Closed
