### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with one of the staffing consultancy account

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#267]
In one of the staffing consultancy account some functionalities are missing in edit profile section but in other accounts it is working properly

![image](https://user-images.githubusercontent.com/101229315/223436471-926df470-7cdd-4aa9-a7ae-9af8b5b2e280.png)

**Comment by Abhinavgunda25** [comment]
It is created in Development mode., Please check now

**Comment by eraytech** [comment]
Verified and Closed
