### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with Verify email in edit profile 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#268]
- Login with Staffing consultancy
- Click the edit profile in basic details
- Click on Verify the email

Actual result : When we click on verify email and click on sent otp first 2 attempts it worked properly but after 3rd,4th etc attempts it is not working 

Expected result : In verify the email Id the otp is sent to registered mail id to confirm the person is authorised or not

**Comment by Abhinavgunda25** [comment]
![WhatsApp Image 2023-05-05 at 11 08 24 AM](https://user-images.githubusercontent.com/49630766/236403742-90e4346a-2ae4-4071-a850-2abc5546d0aa.jpeg)
OTP has send to registered email address

**Comment by eraytech** [comment]
During the initial registration itself, it is validating the email in the latest version. Hence, closing the current issue.
