### ISSUE TITLE
[Web] [Staffing Consultancy] In Additional information Zipcode is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#270]
- Login with Staffing consultancy  
- Click the edit profile in basic details
- Edit the Zip code in Additional information

Actual result : Editing the zip code option is not present in additional information
Expected result : Edit the zip code in the additional information should work properly

![image](https://user-images.githubusercontent.com/101229315/224074674-7fbeb87d-f528-4389-bc59-09bbac816c8d.png)

**Comment by Abhinavgunda25** [comment]
Zipcode is in profile edit section

**Comment by eraytech** [comment]
Verified and Closed
