### ISSUE TITLE
[Web] [Staffing Consultancy] Life at company is not working in company profile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#273]
- Login with Staffing Consultancy
- Click the Company Profile in basic details
- Click on " Why to join us "
- Scroll down

Actual result : Life at company is not working there is no edit option present in the edit profile section
Expected result : In Life at Company it should show the description about the company lifestyle

![image](https://user-images.githubusercontent.com/101229315/225041821-cd1b0a12-bda4-41e3-82b1-54b68dc511d4.png)

**Comment by Abhinavgunda25** [comment]
"Life at" is changed to "Photo Gallery at"

**Comment by eraytech** [comment]
Verified and Closed
