### ISSUE TITLE
[Web] [Staffing Consultncy] Issue with minimum and maximum salary in post a job section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#278]
- Login with Staffing Consultancy
- Click on Post a job
- Enter Minimum salary > Maximum salary

Actual result : It is not showing any error message when we enter minimum salary greater than maximum salary
Expected result : When we enter minimum salary greater than maximum salary it should show the error message  

![image](https://user-images.githubusercontent.com/101229315/225058256-3a3b44c9-be10-43db-b6e2-7b7dc4a674a6.png)

**Comment by eraytech** [comment]
![image](https://user-images.githubusercontent.com/101229315/228309590-096f225b-95d2-4c9f-9b6a-998f29e536bf.png)

Unable to delete "0" from maximum experience to enter a value

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and Closed
