### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with email address in post a job section 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#279]
- Login with Staffing Consultancy
- Click the Post a job section
- Click on email address
- Enter single character or number

Actual result : It is not showing any error message when we enter single character or number in email address 
Expected result : When we enter single character or number in email address it should show the error message

![image](https://user-images.githubusercontent.com/101229315/225064801-09b5b7c0-8ab4-472a-898d-c0f3e7be501b.png)

**Comment by Abhinavgunda25** [comment]
Now., it is Showing email address only logged user email id only

**Comment by eraytech** [comment]
Verified and Closed
