### ISSUE TITLE
[Web] [Staffing Consultancy] Editing of Posted job is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#281]
- Login with Staffing Consultancy
- Click the Posted job in Basic details 
Actual result : Edit option is not there in posted jobs
Expected result : Edit option must present in posted jobs to edit the job post 

![image](https://user-images.githubusercontent.com/101229315/226431469-385f1666-4675-4ad4-a74c-77d2633caef6.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
working, verified
