### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with Allowed distribution list number

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#284]
- Login with Staffing Consultancy
- Click the Distribution list in Basic details
Actual result : Allowed Email distribution list number is not matching with the add distribution list 
Expected result : Allowed Email distribution list number Should match the add distribution list 

![image](https://user-images.githubusercontent.com/101229315/226616398-789587d0-4c03-43d6-8561-3136ebcf9c20.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
