### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with Allowed Number of Email Id's in Distribution List

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#285]
- Login with Staffing Consultancy
- Click the Distribution list in Basic details
Actual result : Allowed Number of Email IDs in each Distribution List is not matching with the add distribution list emails
Expected result : Allowed Number of Email IDs in each Distribution List Should match the add distribution list email numbers

![image](https://user-images.githubusercontent.com/101229315/226618736-6faa04a2-f2e3-4ae5-983c-2b676f0a3078.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
