### ISSUE TITLE
[Web] [Staffing Consultancy] In Action column download functionality is not working in Distribution List 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#286]
- Login with Staffing Consultancy
- Click the Distribution list in Basic details
Actual result : In Action column download functionality is not working in Distribution List 
Expected result : In Action column download functionality should work properly 

![image](https://user-images.githubusercontent.com/101229315/226624037-157a1f73-baa2-4a86-96d2-73f28977bfbf.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check

**Comment by eraytech** [comment]
Verified and Closed
