### ISSUE TITLE
[Web] [Staffing Consultancy] In Add Mass Emails Upload Multiple option is not working in distribution list

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#288]
- Login with Staffing Consultancy
- Click the Distribution list in Basic details
- Create Distribution List Name
- Click View symbol in Actions
- Click Add Mass Email's
- Click Upload Multiple

Actual result : In Add Mass Emails Upload Multiple option is not working in distribution list
Expected result : In Add Mass Emails Upload Multiple option should work in distribution list

![image](https://user-images.githubusercontent.com/101229315/226630385-082e0e9b-fb33-4ef4-bd39-7cc5dfeb7a17.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Verified and closed
