### ISSUE TITLE
[Web] [Staffing Consultancy] Add Distribution List is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#290]
- Login with Staffing Consultancy
- Click the Distribution list in Basic details
- Create Distribution List Name
Actual result :  Add Distribution List is not working it is always showing exceeded limit
Expected result : It should take the details when we add DL Name

![image](https://user-images.githubusercontent.com/101229315/226636739-31259b7e-b517-4079-9f97-e7426d4194f2.png)

**Comment by eraytech** [comment]
What Plan the Staffing Consultancy should have taken must appear in right side of the Distribution List but it is not showing anything

![image](https://user-images.githubusercontent.com/101229315/229570835-63689e2f-06bb-4ff1-8904-c877b697c0ed.png)

**Comment by Abhinavgunda25** [comment]
please check., issue resolved please upgrade plan

**Comment by eraytech** [comment]
It should not allow free plan users to click on the Distribution List, as the free plan users do not have any Distribution List. When Clicking on the Distribution List from Basic Details, a message should be displayed to the free plan users as, "With out Subscription, you are not allowed to create the distribution list".

**Comment by Abhinavgunda25** [comment]
if user has in free plan., clicks on distribution list add form.
it shows "Please upgrade plan"

**Comment by eraytech** [comment]
Verified and closed
