### ISSUE TITLE
[Web] [Staffing Consultancy] Issue with Add User in User List

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#292]
- Login with Staffing Consultancy
- Click the User List in Basic details
- Enter details in Add User

Actual result :  Add User is not working,submit button is missing in add user
                      - Asking for Password
Expected result : It Should take the details in Add User 
                          - User Name
                          - Email
                          - Phone number

![image](https://user-images.githubusercontent.com/101229315/226681804-621874c4-73ad-45ac-ae18-94dc7d2115c2.png)

**Comment by Abhinavgunda25** [comment]
Asking password because user should login

**Comment by eraytech** [comment]
Without any entry it is Showing Limit Exceeded

![image](https://user-images.githubusercontent.com/101229315/228297425-9491e376-d8f9-483c-89b4-d443abc96b56.png)

![image](https://user-images.githubusercontent.com/101229315/228297785-1b67b4e8-31b7-4f5d-9f71-f6d6e25ce477.png)

**Comment by eraytech** [comment]
Verified and Closed
