### ISSUE TITLE
[Web] [Staffing Consultancy] Delete Button is not working in Market Resume

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#294]
- Login with Staffing Consultancy
- Click the Market Resume in Basic details
- Click Add Hot List
- Enter the details and submit
- Now Click on delete button

Actual result : Delete button is not working
Expected result : Delete the entered Hot List details by clicking the delete button in action

![image](https://user-images.githubusercontent.com/101229315/226698043-e45c5bbd-dc94-4289-a670-4c1cf762ee5d.png)

**Comment by Abhinavgunda25** [comment]
Please Refresh after Delete

**Comment by eraytech** [comment]
Verified and closed
