### ISSUE TITLE
[Web] [Staffing Consultancy] In Market Resume Upload Multiple is not working in Add Hot List 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#296]
- Login with Staffing Consultancy
- Click the Market Resume in Basic details
- Click Add Hot List
- Click Upload Multiple 

Actual result : Upload Multiple is not working in Add Hot List 
Expected result : Upload Multiple should work in Add Hot List

![image](https://user-images.githubusercontent.com/101229315/226704258-2008c136-cf6d-4129-b2e7-882fd0c46d7f.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Please provide "Sample Sheet" with column names, same as in "Mass emails". It was available in above screenshot.

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
