### ISSUE TITLE
[Web][Staffing Consultancy] Unable to add Distribution list although subscription plan has availability

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#299]
1. Login as SC
2. Staffing Consultancy->Distribution List
3. Click [Add Distribution List] button

Actual result:
Error message shows "Note: Limit Exceeded, Please upgrade Plan". Although the plan has 5 allowed DL's and only 2 were added.

![image](https://user-images.githubusercontent.com/101229315/226736723-fa40477c-ff14-4ed8-9772-2955089e6b1c.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Verified and the functionality is working
