### ISSUE TITLE
[Web] [Staffing Consultancy]Employer Subscription options are showing in Staffing Consultancy Dashboard section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#303]
- Login with Staffing Consultancy
- Click the Dashboard option
- Click Go pro button

Actual result : Go Pro button is showing employer subscription options
Expected result : Go Pro button should show the Staffing Consultancy Subscription option

![image](https://user-images.githubusercontent.com/101229315/227296661-2a4e1cde-74b3-4a23-b4a0-29fef6e41cd2.png)

![image](https://user-images.githubusercontent.com/101229315/227295966-d13f6893-0fe8-4a19-8538-ccbe9cc2288f.png)

**Comment by Abhinavgunda25** [comment]
If u r Subscribed user., It will show

**Comment by eraytech** [comment]
Verified and Closed
