### ISSUE TITLE
[Web][Admin] Unable to edit Job Seeker subscription details, duplicate input values

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#304]
1. Login as Admin
2. Go to Masters -> Jobseeker subscriptions
3. Click on 'Edit"
4. Edit few details and click [Submit]

Actual result: 
Issue: 1. Button changed to [...] but not saving edited values.
Issue 2.  Allowed Profiles shows 2 times. Remove "Allowed Profiles" drop down.
Issue 3: Change title to "Edit Jobseeker Subscription" from "Add Article"

![image](https://user-images.githubusercontent.com/101229315/228077722-352f91c0-274d-4d7c-b4f2-56a5f1d05bd2.png)

**Comment by Abhinavgunda25** [comment]
issue Resolved & please check

**Comment by Abhinavgunda25** [comment]
![dearjob-304](https://user-images.githubusercontent.com/49630766/231772164-6ea64f15-1985-4ba0-87f8-3d8837803226.PNG)

**Comment by eraytech** [comment]
Still have issue-1 (Button changing to [...] and struck)

![image](https://user-images.githubusercontent.com/101229315/236990895-00c1b958-b626-481d-ba7c-ebac16e73323.png)

**Comment by eraytech** [comment]
Issue still exists

Still have issue-1 (Button changing to [...] and struck)

**Comment by eraytech** [comment]
verified, working fine
