### ISSUE TITLE
[Web][Admin] Add "Total Users" to table in Employer subscription table

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#306]
1. Login as Admin
2. GO to Masters->Employer subscription

Actual result: "Total Users" is not showing in table
Expected result: "Total users" shall show in table.

![image](https://user-images.githubusercontent.com/101229315/228079373-188218b2-1ca1-41b7-8385-947bd8230e29.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
