### ISSUE TITLE
[Web][Admin] Add missing fields in Staffing consultancy subscription page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#307]
1. Login as Admin
2. Go to Masters->Staffing consultancy subscription
3. Observe table columns that are missing while adding new subscription

**5 Missing columns in table:**
Job posts
Total Users
Allowed Email DLs
Allowed Emails per DL
Multiple Jobs

![image](https://user-images.githubusercontent.com/101229315/228080296-c0bac8c0-cd02-4b7f-835d-1e71e84e3bc3.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Issue still repeating

![image](https://user-images.githubusercontent.com/101229315/236384170-dd8cea85-3ee1-4f79-bfe2-d7fa292aaa4e.png)

**Comment by eraytech** [comment]
New columns are added but the values under those columns are mixed up.

a) Profile views value is showing under Multiple Jobs
b) "Allowed E-mail ids per distribution list" value shows under "Profile views"
c) "Multiple Jobs" value is showing under "Allowed E-mail distribution lists"
.....

Please review all values and correct it.
Also, Job posts column is showing twice.

**Comment by eraytech** [comment]
Verified and closed
