### ISSUE TITLE
[Web][Staffing Consultancy] Unable to post job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#308]
1. Login as SC
2. Select Post a Job from menu
3. Fill all details and click [Submit]

Actual result
Button changes to [...] and struck there. Job not posted.

Expected result:
Shall post job successfully.

![image](https://user-images.githubusercontent.com/101229315/228310642-fb3bd150-9653-458b-8fc9-d824e35e0bc2.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
