### ISSUE TITLE
[Web][Staffing Consultancy] Previously entered skill is not cleared while entering new skill in "Post a job" form

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#309]
1. Login as SC
2. Click on "Post a Job" 
3. In Skill set, try to enter few skills. When entered one skill, hit ENTER button and try to enter another skill. Previously entered skill still shows and 2nd skill will append first one.
Ex: Input "Jira" and hit enter.
Then input "SaFE" and hit enter - but it shows as "JiraSaFE"

Expected result:
All skillset shall be saved separately:
Jira, SaFE, DevOps etc

![image](https://user-images.githubusercontent.com/101229315/228312010-57387318-68f0-423e-a42f-ea2e1fff96d7.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
