### ISSUE TITLE
[Web][Admin] Show total skills count in "Skills" page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#310]
1. Login as Admin
2. Go to Masters -> Skills

Expected: Show total skills count in brackets
Ex: Skills (125)

![image](https://user-images.githubusercontent.com/101229315/228314576-2fa70d58-0db3-4262-b8b6-d4948dd41886.png)

**Comment by Abhinavgunda25** [comment]
Issue Resolved
![dearjob-skills-310](https://user-images.githubusercontent.com/49630766/231770583-82ea59cf-159c-40d0-baa1-7f48161594b5.PNG)

**Comment by Abhinavgunda25** [comment]
Issue Reslved & Please check

**Comment by eraytech** [comment]
Verified and Closed
