### ISSUE TITLE
[Web] [Staffing Consultancy] Post a Job submit button is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#311]
- Login with Staffing Consultancy
- Click the Post a Job
- Fill the details and click submit button

Actual result : In Post a job it is showing Limit Exceeded and subscription page is also not working to upgrade the plan
Expected result : Post a job and subscription page should work properly

![image](https://user-images.githubusercontent.com/101229315/228325425-878d03b5-b679-4649-825c-538c23f2313d.png)

**Comment by Abhinavgunda25** [comment]
please check ., issue resolved

**Comment by eraytech** [comment]
Verified and the functionality working fine.
