### ISSUE TITLE
[Web][Admin] Promo code popup struck if submitted without entering Promo Code

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#312]
1. Login as Admin
2. Master -> Promo Code -> Add Promo Code
3. Input Promo Title and click [Submit] without entering any other details

Actual result: Error message shows as expected, but [Submit] button changes to [....] and will not return back to [Submit] until page refreshed.

Expected result: Shall show error message and show [Submit] button normally.

![image](https://user-images.githubusercontent.com/101229315/228370725-95f8d047-6c0e-4dd4-a4f3-078113c2a418.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., Please check
![dearjob -312](https://user-images.githubusercontent.com/49630766/231773525-fd1d24bc-3903-4ef5-8d85-9e9eac57682a.PNG)

**Comment by eraytech** [comment]
Fill up to promo title and click on submit button 
result : Submit button is scrolling 

![image](https://user-images.githubusercontent.com/101229315/235190514-8ac58b29-67ad-4636-bded-29e3785a8621.png)

**Comment by eraytech** [comment]
Issue still exists

![image](https://user-images.githubusercontent.com/101229315/235244381-d6b7fc87-e7e5-41a6-ba90-e927c4c1baa1.png)

**Comment by eraytech** [comment]
It is better to disable [Submit] button until all details are filled.

**Comment by eraytech** [comment]
Is the designed changed? We don't need [Choose file] option.
"Discount" column shall show after "Type"

![image](https://user-images.githubusercontent.com/101229315/235244727-6f2b1a52-3167-4292-8608-4b3a367d8aea.png)

**Comment by Abhinavgunda25** [comment]
issue resoled.,

**Comment by eraytech** [comment]
Not resolved:

Bring back this design. Remove [Choose file]
https://github.com/gak112/DearJobTesting/issues/312#issuecomment-1528040473

**Comment by eraytech** [comment]
Submit button issue resolved, but as commented above, [Choose file] is not removed.

**Comment by eraytech** [comment]
kindly follow this : It is better to disable [Submit] button until all details are filled

even after giving all positive inputs, submit button is loading, kindly check

**Comment by eraytech** [comment]
kindly follow this : It is better to disable [Submit] button until all details are filled


https://github.com/gak112/DearJobTesting/assets/101229315/3f0fa88b-5b3d-4b3e-b1e3-d94f493746e9

**Comment by eraytech** [comment]
verified, working fine
