### ISSUE TITLE
[Web][Staffing Consultancy/Employer] Billing Address selected is not reflecting in "Payment Summary" page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#314]
1. Login as SC or Employer
2. Go to subscriptions and select a plan
3. Click on "edit" icon on Billing Address
4. Select another address and click on "payment summary" link to go back

Actual result:
Selected address is not replaced with existing address.

Expected result:
1. Selected address shall replace existing address.
2. Change design to show addresses. Current design is not appealing.

![image](https://user-images.githubusercontent.com/101229315/228374407-7880e270-b830-4ffb-8e4b-7804049b0edf.png)

**Comment by Abhinavgunda25** [comment]
Selected address card will changed to true
![swww](https://user-images.githubusercontent.com/49630766/235458701-d2862873-91ac-43b2-8710-ea8839b5c347.PNG)
after click on payment summary selected address is shown in billing address
![swww2](https://user-images.githubusercontent.com/49630766/235458834-69f3783f-7ba5-401f-8ab5-0f77547f940e.PNG)

**Comment by eraytech** [comment]
Verified and Closed
