### ISSUE TITLE
[Web] [Staffing Consultany] In Edit Profile Mobile number is accepting Characters

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#315]
- Login with Staffing Consultancy
- Click the edit profile in Basic details

Actual result : Mobile number is accepting the characters
Expected result : Mobile number should only take numbers , when we enter characters it should show the error message

![image](https://user-images.githubusercontent.com/101229315/229810256-d9bfa245-81d7-42d5-839e-617fb8399d54.png)

**Comment by Abhinavgunda25** [comment]
issue Resolved., please check

**Comment by eraytech** [comment]
Still mobile number is accepting the characters

![image](https://user-images.githubusercontent.com/101229315/235193298-b9817bb3-71c5-4b61-9720-a9ff7c3e57cf.png)

**Comment by Abhinavgunda25** [comment]
solved.,

**Comment by Abhinavgunda25** [comment]
solved.,

**Comment by eraytech** [comment]
Verified and Closed
