### ISSUE TITLE
[Web][Admin] Unable to search with Jobseeker_id, Employer_id, StaffingConsultancy_id 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#316]
1. Login as Admin
2. Menu -> Jobseeker/Employer/StaffingConsultancy
3. Copy a jobseeker-Id/employer_id/staffingconsultancy_id and paste in search box.

Expected result:
Shall show the result

Actual result:
Shows no result

![image](https://user-images.githubusercontent.com/101229315/230675598-5104f12d-e9bc-4983-9a4c-5fd896aaceeb.png)

![image](https://user-images.githubusercontent.com/101229315/230675646-c15479b2-803b-49de-b944-7152de591328.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
