### ISSUE TITLE
[Web][Admin] Staffing consultancy subscriber expires on shows wrong data

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#317]
1. Login as Admin
2. Go to Menu->Staffing consultancy and observe table values.

Actual:
Expires on shows as 200/150

Expected:
Shall show expires on as Date (Ex: 11-Feb-2024).
Also show, "Started on: date as well

![image](https://user-images.githubusercontent.com/101229315/230679543-5c97ef94-72bd-4ea0-b044-336564220fad.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
date format display is fine, expired subscription still reflecting as platinum, kindly check

![image](https://github.com/gak112/DearJobTesting/assets/101229315/790c0170-6d3c-45c0-a51d-79323f65447f)

![image](https://github.com/gak112/DearJobTesting/assets/101229315/76d1e7a9-b922-48ac-b8db-8eda3f2f9a14)

**Comment by eraytech** [comment]
verified
