### ISSUE TITLE
[Web] [JS/Emp/Sc] Change password is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#318]
1. Login with Js/Emp/Sc
2. Click the Change Password
3. Enter old password and enter new password
4. Click Submit button

Actual result : Change Password is showing error message  as " Invalid old Password" all the time when we enter right password also
Expected result : Change password should work

![image](https://user-images.githubusercontent.com/101229315/230919983-b1334889-4dd4-47f9-82a0-822ba90e97f7.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check with newly registered users

**Comment by eraytech** [comment]
Verified and Closed
