### ISSUE TITLE
[Web] [Jobseeker] Apply Job is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#319]
1. Register with New Job seeker Account
2. Click on Login
3. Edit Profile
4. Click search button in home page
5. Click Posted in Refine by section
6. Apply the jobs

Actual result : Applying Jobs is not working, it is showing [....]
Expected result : Apply by jobs should work properly

![image](https://user-images.githubusercontent.com/101229315/230928022-edf53482-4e6c-4446-a059-f9aab864e2ba.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
The issue is still repeating

![image](https://user-images.githubusercontent.com/101229315/236111361-96b1cfb8-8b62-42ee-aa7d-0bff48fed86c.png)

**Comment by Abhinavgunda25** [comment]
please check
[319.webm](https://github.com/gak112/DearJobTesting/assets/49630766/472a4a06-14de-4d54-bb70-3e360baf52c3)

**Comment by eraytech** [comment]
working, verified
