### ISSUE TITLE
[Web] [Employer] Post a Job is not working 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#322]
1. Login with Employer
2. Click on Post a Job
3. Fill the details
4. Click on submit button

Actual result : Submit button is not working in Post a Job
Expected result : Submit button should work properly in Post a job

![image](https://user-images.githubusercontent.com/101229315/230954653-b2aafcb5-2521-4de8-a9a9-69eaf91abe6a.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
