### ISSUE TITLE
[Web][SC] Job details are blank when clicked on posted job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#327]
1. Login as SC
2. Click on posted jobs in "Refine by"
3. Click on any job. Job Details page will display.
4. Observe job details

Expected: Shall show all job details
Actual: Job details are empty.

![image](https://user-images.githubusercontent.com/101229315/232587322-e6b78f43-ee1d-4e32-ae2d-3effee1fd5ae.png)

**Comment by Abhinavgunda25** [comment]
issue resolved

**Comment by eraytech** [comment]
Verified and closed
