### ISSUE TITLE
[Android v1.7] Home screen is blank

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#328]
1. Install Android 1.7 from Google Play store
2. Open app
3. Observe home page

Actual result:
Blank home page

![image](https://user-images.githubusercontent.com/101229315/232613295-ed25da71-cb87-4304-bf13-6f5e82e0bfae.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
