### ISSUE TITLE
[Android v1.7] Register link in login page is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#329]
1. Install Android 1.7 from Google Play store
2. Open app
3. Click on "Register"

Expected: Shall open "What type of user are you?" page to start registration process
Actual result: No action triggered when clicked on "Register"

![image](https://user-images.githubusercontent.com/101229315/232614752-eced9bb0-2ffc-4f46-b323-63f1eaf36001.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
verified and working
