### ISSUE TITLE
[Android v1.7] Unable to login as JS/EMP/SC

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#332]
1. Install Android 1.7 from Google Play store
2. Open app
3. Try logging using Jobseeker/EmployerStaffing Consultancy credentials (Registered from Web)

Expected: Shall go to home page.

Actual result: Toast message says "Login success", but does not go to home page. Stays in login page only
![image](https://user-images.githubusercontent.com/101229315/232616797-1218f0e0-9c9a-4cff-9cbd-051b84a36b4f.png)

**Comment by Abhinavgunda25** [comment]
issue reolved., please check

**Comment by eraytech** [comment]
Verified. Login is redirecting to the home page.
