### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Submit button freezed after clicking while updating company address

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#334]
1. Open Android v.17 app
2. Login as SC
3. On Home page, click on "View All" under company name (Highlights for you section)
4. Company profile page displayed 
![image](https://user-images.githubusercontent.com/101229315/232880047-9525ce83-a8e7-4281-8075-8d1e18da22c2.png)

5. Click Edit to update address
6. Enter a valid address under Location field
7. Click Submit

Actual result:
Submit button changed to [...] and freezed. When pressed back after waiting some time, address not updated.
![image](https://user-images.githubusercontent.com/101229315/232880331-2938f645-90bc-43f5-a475-5276ed8da475.png)

**Comment by eraytech** [comment]
Same issue in other page 

![image](https://user-images.githubusercontent.com/101229315/232880866-a06a8229-f4a4-48ac-8314-361e52050ef1.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Verified and closed
