### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Ratings page displaying when clicked on "Benefits to Employees" tiles

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#335]
1. Install Android v1.7
2. Login as SC
3. On Home page, click on "View All" under company name (Highlights for you section)
4. Company profile page displayed
5. Click "Why Join Us" tab and click on "health insurance" or "Paid Leaves" under "Benefits to Employees" section
![image](https://user-images.githubusercontent.com/101229315/232881843-f46fbc6e-592e-4e64-b335-492ba8f9096d.png)

Expected result:
Nothing shall happen

Actual result:
Ratings page is displaying
![image](https://user-images.githubusercontent.com/101229315/232881894-095b8d82-79ef-4a3f-9c70-e40bcf1468bc.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
