### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Jobs tab in company details shows all jobs not posted by company

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#336]
1. Install Android v1.7
2. Login as SC
3. On Home page, click on "View All" under company name (Highlights for you section)
4. Company profile page displayed
5. Click "Jobs" tab

Expected result:
Shall show "Post a Job" tile + only jobs posted by this staffing consultancy
Actual result:
Shows "Post a Job" tile + plenty of jobs (may be imported and all other jobs)

![image](https://user-images.githubusercontent.com/101229315/232883195-5aba3024-2995-426c-91b3-ac369a318ea5.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed. But will open new issue that [Market My Job] has to show on these tiles, not [1-Apply] as these jobs are posted by self company.
