### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Spelling mistakes in home page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#337]
Pan -> Plan
Subcribe -> Subscribe

![image](https://user-images.githubusercontent.com/101229315/232896729-9454c097-94a2-4cf3-912a-0044f7a797ed.png)

**Comment by eraytech** [comment]
Sucription -> Subscription

![image](https://user-images.githubusercontent.com/101229315/232905160-df001fbe-0e50-4553-b8c0-66fcd33965b0.png)

**Comment by eraytech** [comment]
SUBCRIBE -> SUBSCRIBE

![image](https://user-images.githubusercontent.com/101229315/232906504-d901bcde-0ac3-4ab0-98fc-3455a27aee66.png)

**Comment by eraytech** [comment]
5) Technyks -> DearJob

![image](https://user-images.githubusercontent.com/101229315/232908038-eec48708-9fc7-46ed-ae7d-ea84f9f71134.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., "Technyks" name is Merchant Name

**Comment by eraytech** [comment]
> 

Subscription (Paid) is not yet resolved. (2nd screenshot)

**Comment by eraytech** [comment]
>>"Technyks" name is Merchant Name
Yes but subscribers does not know who is "Technyks", it is better to change to "DearJob"

**Comment by Abhinavgunda25** [comment]
issue reolved., please check

**Comment by eraytech** [comment]
Verified and closed
