### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Unable to send email

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#338]
1. Open Android v.17 app
2. Login as SC
3. From bottom menu, click on "Inbox" icon
4. Click on "new Email" icon and send an email
5. Toast message shows Email sent successfully.

Expected result: Email shall be delivered to the recipient.
Actual result: Email was not received by the recipient. But shows in SENT items.

![image](https://user-images.githubusercontent.com/101229315/232899205-67202cf5-17b6-4d6c-8686-e1cc2c52a119.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Unable to receive email. After clicking send, toast shows "Successfully saved" but email was not sent.
Also please change wordings to "Successfully sent"

**Comment by Abhinavgunda25** [comment]
Sending email to registered email address
1. Enter details from employeer account
![inbox1](https://user-images.githubusercontent.com/49630766/235860548-9ecd3e61-53b1-4d12-8ca1-34737c38f0b0.PNG)
2. In Employeer inbox tab, in sent segment send email will be shown here
![inbox2](https://user-images.githubusercontent.com/49630766/235860863-c1a9a048-ed86-4a1e-94fa-1d8512e8a621.PNG)
3. Receiver email inbox segment
![inbox3](https://user-images.githubusercontent.com/49630766/235860957-8e7fd3b1-701a-40bb-8185-f5842a480d6d.PNG)
4. employeer mail fullview
![inbox4](https://user-images.githubusercontent.com/49630766/235861016-e7a2901e-764c-486d-b12b-238680e97bcd.PNG)

**Comment by eraytech** [comment]
asterisk symbol not mentioned for mandatory fields

![WhatsApp Image 2023-08-24 at 16 49 13](https://github.com/gak112/DearJobTesting/assets/101229315/ed1be70d-fc63-4fca-adb8-3a8dad39ebbd)

**Comment by eraytech** [comment]
Change the description label  to "Email message"

![WhatsApp Image 2023-08-29 at 15 34 10](https://github.com/gak112/DearJobTesting/assets/101229315/b8298d60-9bb4-46cd-a51b-53d6f5667e42)

Kindly keep proper toast message.like "please enter valid email address", make changes in both web and mobile.
![WhatsApp Image 2023-08-29 at 15 35 19](https://github.com/gak112/DearJobTesting/assets/101229315/7d841425-d1e7-4555-adf2-60fe0fc9efb2)

Reply button is not available
![WhatsApp Image 2023-08-29 at 15 45 13](https://github.com/gak112/DearJobTesting/assets/101229315/2fb6bc4a-2c1f-46fa-871a-c27d9db9e786)

**Comment by eraytech** [comment]
no new build was shared yet!

**Comment by eraytech** [comment]
not able to attach image

**Comment by eraytech** [comment]
verified and working in android 5.1v
