### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Unable to select new Billing address

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#339]
1. Open Android v1.7 app
2. Login as SC -> select "More" from bottom menu of home page -> Subscriptions -> Click [Subscribe] 
3. Click on [Edit] icon in Billing Information
4. Select other address that is not already selected. 

Actual result:
Unable to select address. When clicked on [Select] nothing happens.

Expected result:
1. Should be able to select any other address.
2. Selected address shall display in Billing information in previous page.

![image](https://user-images.githubusercontent.com/101229315/232906220-b03627f7-5cdf-41ae-8192-04114e8b0aa1.png)

**Comment by Abhinavgunda25** [comment]
issue reolved., please check

**Comment by eraytech** [comment]
verified and working fine
