### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Unable to add new Billing address

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#340]
1. Open Android v1.7 app
2. Login as SC -> select "More" from bottom menu of home page -> Subscriptions -> Click [Subscribe] 
3. Click on [Edit] icon in Billing Information
4. Click on HOME icon to add new address
5. Enter a new address and click [Submit]

Actual result:
When clicked on [Submit] nothing happens.

Expected result:
1. Should be able to save new address.
2. Selected address shall display in Billing information in previous page.

![image](https://user-images.githubusercontent.com/101229315/232906073-0e0ad26a-f70d-4ba0-93de-2a543369d321.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
address getting submitted , 

note : But there is no title indicating to enter this section, such as "billing address."

**Comment by Abhinavgunda25** [comment]
Title Name: Billing Address 
![billadd](https://github.com/gak112/DearJobTesting/assets/49630766/a013ec45-8934-45fc-81dc-93337c718490)

**Comment by eraytech** [comment]
verified
