### ISSUE TITLE
[Android v1.7] [login] Taking more than one attempts to login

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#342]
- Enter the Login details
- Enter the email id
- Enter the password

Actual result :  Taking more than one attempt to login
Expected result : It must  login with one attempt

![image](https://user-images.githubusercontent.com/101229315/233112622-d6dbfc50-ce07-466b-83e0-941263f57dbf.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
