### ISSUE TITLE
[Android v1.7] [Employer] Submit button is not working in edit details

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#343]
- Login with employer
- Click View all option
- Click edit option in About us section
- Enter the details 
- Click the submit button

Actual result : Submit button is not working it is showing [....]
Expected result : Submit button should work properly

![image](https://user-images.githubusercontent.com/101229315/233122141-81e13779-a4fa-4726-9a02-4474b0b7f501.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Location and Mobile number is not working

**Comment by Abhinavgunda25** [comment]
please check ., issue resolved

**Comment by eraytech** [comment]
I have changed the location, but it is not updated after clicking on submit.

**Comment by eraytech** [comment]
Verified and working fine.
