### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Clicking on "Followers" tile lands in Company details page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#344]
1. Open Android v1.7 app
2. Login as SC. On home page, click on [View Details] in Followers tile.

Expected result: Shall show followers page.
Actual result: Lands in company details page (Same as clicking on [View All] in company tile in home page)

![image](https://user-images.githubusercontent.com/101229315/233124107-ff6c2327-5a59-4b2f-bfc5-8735bafe3ed8.png)

![image](https://user-images.githubusercontent.com/101229315/233124164-d9b1c438-697d-4a7f-a6bb-f52c238582e6.png)

**Comment by Abhinavgunda25** [comment]
Please check
[344.webm](https://github.com/gak112/DearJobTesting/assets/49630766/34ff53cb-fd98-4a15-a7bb-4f60e8dc53c3)

**Comment by eraytech** [comment]
verified and working
