### ISSUE TITLE
[Android v1.7] [Employer] Spelling mistakes in homepage

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#345]
pan > Plan
Subcribe > Subscribe

![image](https://user-images.githubusercontent.com/101229315/233124989-a2a7e90a-e6d3-491b-8897-402d7658739d.png)

**Comment by Abhinavgunda25** [comment]
issue reolved., please check

**Comment by eraytech** [comment]
Verified and Closed
