### ISSUE TITLE
[Android v1.7] App is showing totally black screen it is taking more than 1 attempt to get normal position

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#346]
When we open the app it is showing black screen
Expected result : The app should work properly

![image](https://user-images.githubusercontent.com/101229315/233128649-7fa97498-5181-44e6-ae30-24d5714a651b.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
