### ISSUE TITLE
[Web][Staffing Consultancy] Need Sample demo sheet for adding mass emails

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#348]
1. Login as SC
2.  Go to Distribution List-> Mass Emails -> Add Mass Email -> Upload multiple tab

Actual result:
User may not know how to enter details in a excel sheet and upload.

Expected:
Provide a sample excel sheet with column headers

![image](https://user-images.githubusercontent.com/101229315/233187644-15899fda-0785-45c0-81e0-5e7b60f13e14.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Sample excel sheet added, but it is for Hotlist emails.
Please upload correct sample excel sheet for Mass emails

Provide only 1 sample row with sample data. Do not provide real email id

![image](https://user-images.githubusercontent.com/101229315/235235658-77bc8a4e-d9d6-465b-9cbf-0a86328a314b.png)

**Comment by eraytech** [comment]
Tried to upload like below, but gives error "Please check name from the excel"

![image](https://user-images.githubusercontent.com/101229315/235237043-18ec96ad-307c-4c6a-9381-731fad427b0f.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Issue still existing. Same "Hotlist emails" sheet downloads instead of mass emails sheet.

**Comment by Abhinavgunda25** [comment]
Please check again., Website is hosted

**Comment by eraytech** [comment]
Verified and closed
