### ISSUE TITLE
[Android v1.7] [Employer] Unable to see the location options in post a job when we on the dark mode 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#349]
- Login with Employer
- Click on Post a job 
Actual result : Unable to see the location options in post a job 
Expected result : Every option should visible properly

![image](https://user-images.githubusercontent.com/101229315/233416338-27d02fd2-dbb1-4d09-8bc9-39a13a2003ef.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
