### ISSUE TITLE
[Android v1.7] [Employer] All the labels are missing in post a job section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#350]
- Login with Employer 
- Click on Post a job
Actual result : Experience, Minimum salary, Skill set, Category, Visa requirement, Live period, Job description all this  labels are missing       in  post  job section
Expected result : Add all the labels to  post a job section

![image](https://user-images.githubusercontent.com/101229315/233423358-6fd200b5-e038-4aee-a2ec-ab1430d95fea.png)

![image](https://user-images.githubusercontent.com/101229315/233424865-2a040a20-ef59-4d56-ab24-75271fea1bd4.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
