### ISSUE TITLE
[Android v1.7] [Employer] Issue with minimum and maximum salary in post a job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#351]
- Login with Employer
- Click post a job
- Enter the details 
- Click on submit button 

Actual result : When we enter minimum salary greater than maximum salary post a job is  accepting 
Expected result : It should show the error message when we enter minimum salary > maximum salary

![image](https://user-images.githubusercontent.com/101229315/233431213-b81486f7-ddc0-4a64-84b3-222c6e116104.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Issue is still repeating

![image](https://user-images.githubusercontent.com/101229315/235627285-291e1a37-6f25-4b00-8634-7e57ad50a528.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and concluded that the current issue is resolved.
