### ISSUE TITLE
[Android v1.7] [Employer] It is not showing any error message when we leave some functionalities in post a job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#353]
- Login with Employer
- Click on post a job

Actual result : When we leave Hiring type, Payment type, Visa requirement  and click on submit button it is accepting
Expected result : It should show error message when we leave some functionalities

![image](https://user-images.githubusercontent.com/101229315/233668857-91f76d20-f440-46df-9c2e-a106d69132ba.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
