### ISSUE TITLE
[Web] [Homepage] In search details it is not showing complete job details posted by dear job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#354]
- Open dear job website
- Click on search button
- Select posted in refined by
- open complete details of any job

Actual result : It is not showing complete job details posted by dear job
Expected result : It should show complete job details posted by dear job

![image](https://user-images.githubusercontent.com/101229315/233673075-b4fd6efc-24fb-4f6f-a378-14870e8db44d.png)

![image](https://user-images.githubusercontent.com/101229315/233673303-b7b1982b-42a5-45f7-adfc-68875a83da81.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Company address is not showing in this page:

![image](https://user-images.githubusercontent.com/101229315/235243146-4502f990-4f8c-4569-acde-ea7335271d4e.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Verified and closed
