### ISSUE TITLE
[Web] [Staffing Consultancy] Many other distribution lists are showing in Marketing Job page that does not belong to current company

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#359]
1. Login as SC, Post a Job or go to Posted Jobs
2. Click on [Market Job] on any posted job
3. Observe recipients list for mass emailing.

Expected result:
Shall show only distribution lists that belong to this company (This company has only 4 DLs)
![image](https://user-images.githubusercontent.com/101229315/233744007-a8564ffd-47ad-4877-91d6-937424492d77.png)

Actual result:
Shows all distribution lists that belong to different companies. (Shows over 15 DLs)
![image](https://user-images.githubusercontent.com/101229315/233743924-f7c7ffea-ffb4-4361-8e15-3e238238a4ae.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed for Web. But issue still occurs in Android 1.9

**Comment by eraytech** [comment]
Issue 1: This is happening in Android 1.9 also. So reopened issue
Issue 2: Wrong number of applicants count showing

![image](https://user-images.githubusercontent.com/101229315/236105511-f591fdce-4ce1-4636-b95f-fc0bd7866fbe.png)

Issue 3: About company tab is showing Distribution list and [Send Email] button. 
Shall show only About company details, why join us etc

![image](https://user-images.githubusercontent.com/101229315/236105687-816800e1-64e2-4421-bd6f-e8da6e7cdabd.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Still the same issues are persisting in android 2.4
Issue 2: Wrong number of applicants count showing
Issue 3: About company tab is showing Distribution list and [Send Email] button.
Shall show only About company details, why join us etc

![Screenshot107-SC Distribution list](https://github.com/gak112/DearJobTesting/assets/101229315/311e67ce-ad96-41a2-b142-c6b4a170b00e)

**Comment by eraytech** [comment]
verified in 2.8v, working fine

![WhatsApp Image 2023-07-18 at 17 26 34](https://github.com/gak112/DearJobTesting/assets/101229315/de9a916c-0dd1-416f-8066-e80a9c7b6437)
