### ISSUE TITLE
[Android v1.7] [Employer] Select,Edit,Delete and Add Address is not working in subscription page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#360]
- Login with Employer 
- Click on Subscriptions option
- Select the plan and subscribe
- Add, edit, delete address in billing information

Actual result :  Add, edit, delete address in billing information is not working also it is showing default address
Expected result :  Add, edit, delete address in billing information should work and don't show any default address

![image](https://user-images.githubusercontent.com/101229315/234051319-f7c3db85-5166-4f1d-b398-3dc7577102c6.png)

![image](https://user-images.githubusercontent.com/101229315/234051659-bb8cefd0-4fd5-4a62-a5ed-6e367d89dfcb.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by Abhinavgunda25** [comment]
Please check
[360.webm](https://github.com/gak112/DearJobTesting/assets/49630766/deba7605-4a01-48bc-a3f7-5b4df4c39e35)

**Comment by eraytech** [comment]
no "edit/delete" options are found, we can find only "add" option

**Comment by eraytech** [comment]
edit/delete working fine.

but now I am unable to see name and phone number in "address details page", kindly check it

**Comment by eraytech** [comment]
![WhatsApp Image 2023-06-06 at 13 19 50](https://github.com/gak112/DearJobTesting/assets/101229315/8823d30f-4c28-4e49-909b-f504573f6d5c)

**Comment by eraytech** [comment]
still facing same issue (  device : Samsung galaxy A23, android 13 )

**Comment by eraytech** [comment]
verified, working now
