### ISSUE TITLE
[Android v1.7][Staffing Consultancy] "About US" shows twice when edited and saved.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#362]
1. Login as SC
2. In home page, click on [View All] under eRay Technologies LLC (Highlights for you)
3. Under "About US", click [Edit] button and edit some details and [Submit]

Expected result:
Shall edit details and save.

Actual result:
Adding About US second time. There are now 2 About US tiles.

![image](https://user-images.githubusercontent.com/101229315/234106005-e077cfd4-8f81-4f28-a470-ee43fb3493ce.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed.
