### ISSUE TITLE
[Android v1.7][Staffing Consultancy] Employer subscription plans shows in SC

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#363]
1. Login as SC
2. From home page, click on [Subscribe] button 

![image](https://user-images.githubusercontent.com/101229315/234109601-e7795e2f-e219-48de-a6fb-5ccc4db83020.png)

4. Observe subscription plan details

Expected result:
Shall show SC subscription plans

Actual result:
Showing Employer plans.
Where as from Home page->More->Subscriptions: It is showing correct plans.

![image](https://user-images.githubusercontent.com/101229315/234110054-d866ad3f-f738-416b-9bc0-7b520346c92f.png)

Admin-> Employer subscriptions:
![image](https://user-images.githubusercontent.com/101229315/234110114-26df3538-4b5b-4fb4-a3aa-abf72fe3c7dd.png)

Admin-> SC subscriptions:
![image](https://user-images.githubusercontent.com/101229315/234110187-ed5dc152-da3d-4682-aa28-da7b0965dc1e.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by Abhinavgunda25** [comment]
Please check
[Uploading 363.webm…]()

**Comment by Abhinavgunda25** [comment]
[363.webm](https://github.com/gak112/DearJobTesting/assets/49630766/26081050-fcb8-4981-b4bc-b5fc6692108c)

**Comment by eraytech** [comment]
Verified
