### ISSUE TITLE
[Admin] No option to create/edit "Pay Per Day" charges

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#364]
1. Login as Admin
2. Try to set "Pay Per Day" charges

Expected result:
Shall have a separate page along with subscription plans for "Pay Per Day" changes

Actual result:
There is no option to set charges and to set minimum number of days for job posting.

![image](https://user-images.githubusercontent.com/101229315/234113245-4b2f5535-e899-4f40-a5c6-f0df2a34a4a0.png)

![image](https://user-images.githubusercontent.com/101229315/234113511-4b6f171e-cbe9-488e-8c2c-cdced1ef7f44.png)

In "Pay per Day" plan, allow below inputs:
1. Price
2. Minimum days to post job

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
resolved
