### ISSUE TITLE
[Admin] Unable to edit Jobseeker subscription plan

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#365]
1. Login as Admin
2. Go to Master->JS subscription
3. Click on Edit in any existing plan
4. Edit something and click [Submit]

Actual result: Button changes to [...] and does not save.
Also, change title of form to "Jobseeker Subscription" instead of "Add Article"

![image](https://user-images.githubusercontent.com/101229315/234126904-0a3830e3-cb4c-49e0-a4a5-4f028d703636.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
Please check
[365.webm](https://github.com/gak112/DearJobTesting/assets/49630766/c37b2ab2-1561-49d4-add3-3203937200c7)

**Comment by eraytech** [comment]
Checked and concluded, working as fine.

**Comment by eraytech** [comment]
https://github.com/user-attachments/assets/9a1db56a-3cee-47bc-9905-a9e59f2fe49b
