### ISSUE TITLE
[Android v1.7] [Employer] Submit button is not working in company description

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#366]
- Login with Employer 
- Click on menu
- Click on company profile
- Click on company description 

Actual result : Submit button is not working in company description, it is showing [....]
Expected result : Submit button should work properly

![image](https://user-images.githubusercontent.com/101229315/234313980-61221800-56eb-4be8-b9da-5889ba4121bd.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
