### ISSUE TITLE
[Android v1.7] [Employer] Add functionality is not working in Department hiring in dear job

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#367]
- Login with Employer
- Click on menu 
- Click on company profile 
- Click on add in Department hiring in dear job

Actual result : After Adding the details it is not showing in Department hiring dear job
Expected result : After Adding It should appear in Department hiring in dear job

![image](https://user-images.githubusercontent.com/101229315/234317128-1bcec530-68e5-431b-b515-4777b91cd49f.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
