### ISSUE TITLE
[Android v1.7] [Employer] Submit button is not working in Additional information

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#368]
- Login with Employer
    - Click on menu
    - Click on company profile
    - Click on Edit button in Additional information 
    - Enter the details 
    - Click on submit button

Actual result : Submit button is not Additional information, it is showing [......]
Expected result : Submit button should work properly

![image](https://user-images.githubusercontent.com/101229315/234320834-e7fbe286-5515-4f80-8ec6-9982a7ed7616.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Facing issue with Established year, After submit it is disappearing
- Headquarters is not displaying in the main page

**Comment by Abhinavgunda25** [comment]
we have added headquaters and established year is working

**Comment by Abhinavgunda25** [comment]
please check
[368.webm](https://github.com/gak112/DearJobTesting/assets/49630766/6ef20b48-a13b-4a47-b262-84a4dc071aff)

**Comment by eraytech** [comment]
For employer and SC:: Allowing future dates in Established year, kindly check
Also, all links are not hyperlinked (website and social)

![image](https://github.com/gak112/DearJobTesting/assets/101229315/eb18f95b-e124-4ef3-baa6-65b318628c27)

**Comment by eraytech** [comment]
links are not hyperlinked (website and social)

**Comment by eraytech** [comment]
working, verified
