### ISSUE TITLE
[Android v1.7] [Employer] In Why to join us section it is showing Our Leader Message instead of Our Mission

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#369]
- Login with Employer
- Click on Menu
- Click on Company profile
- Click on Why to join us

Actual result : In Why to join us section it is showing Our Leader Message instead of Our Mission and Submit button is not working
Expected result : Change Our Leader Message to Our Mission and submit button should work properly

![image](https://user-images.githubusercontent.com/101229315/234332304-688dde43-ec01-4784-87d7-51896d9170d3.png)

![image](https://user-images.githubusercontent.com/101229315/234333039-139ece2a-ae31-48bb-ae88-a56c667412f2.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and Closed
