### ISSUE TITLE
[Android v1.7] [Employer] Photo gallery is not working in Why to join us section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#370]
- Login with Employer
- Click on Menu
- Click on Company profile
- Click on Why to join us
- Click on edit option in photo gallery

Actual result : Photos are not uploading in photo gallery section
Expected result : Uploading of photo should work properly

![image](https://user-images.githubusercontent.com/101229315/234335679-eebe726f-8487-41cd-b7ee-52a432d13fa5.png)

**Comment by Abhinavgunda25** [comment]
issue ressolved., please check

**Comment by eraytech** [comment]
Issue still repeating

**Comment by Abhinavgunda25** [comment]
In Android [1.9] we have uploaded image in photo gallery section., please check below video for ref

https://user-images.githubusercontent.com/49630766/235853170-72e8e0bf-80af-4773-b4ed-b824021490de.mp4

**Comment by eraytech** [comment]
issue is not resolved still facing same issue in android 2.4 version, kindly check

**Comment by eraytech** [comment]
Andriod 3.6v, still issue is not resloved,kindly check.

**Comment by eraytech** [comment]
new build was not shared yet!

**Comment by eraytech** [comment]
verified and working in android 5.1v
