### ISSUE TITLE
[Android v1.7] [Employer] In Benefits to employees Add option is not working

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#371]
- Login with Employer
- Click on Menu
- Click on Company profile
- Click on Why to join us
- Click on add option in Benefits to employees

Actual result : Blank button is showing in Benefits to employees
Expected result : Show the Submit button in blank option and submit button should work properly 

![image](https://user-images.githubusercontent.com/101229315/234344709-09665b66-e55d-4f0e-a6c0-80008dba2af2.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and fixed
