### ISSUE TITLE
[Web] Social icons are not pointing to actual links in 'Contact Us' page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#372]
Click on these social icons, they are not pointing to the URL's mentioned in Admin page.

![image](https://user-images.githubusercontent.com/101229315/234978273-71aadf6d-926d-4bec-a345-21b069cd16fa.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
Verified and closed
