### ISSUE TITLE
[Android v1.8][Staffing Consultancy] Jobs tab in company details shows incorrect buttons and details

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#373]
1. Install Android v1.8 apk
2. Login as SC
3. On Home page, click on "View All" under company name (Highlights for you section)
4. Company profile page displayed
5. Click "Jobs" tab and observe the tiles displaying.

Expected result:
1. Shall show Posted on: date
2. Change [1-Apply] to [Market My Job]
3. Slight alignment for icons and text (Salary, exp, location, skill set)
4. Keep space after comma in skill set
5. Remove Check box option in front of job title
6. Remove [Save] button at bottom and Insert active/inactive toggle button same as in web.

![image](https://user-images.githubusercontent.com/101229315/235185525-ef7f3887-cd51-4e12-b3af-764ceba013ec.png)

**Comment by eraytech** [comment]
verifying in 2.4 version

Keep space after comma in skill set is not resolved.

new issue : added new skills and submitted, still reflecting old data

**Comment by eraytech** [comment]
old issue : added new skills and submitted, still reflecting old data

new issue : data is not visible in job description( device : Samsung galaxy a23 android 13 and moto g10 power  android 11)

**Comment by qspaysys2** [comment]
new issue : data is not visible in job description( device : Samsung galaxy a23 android 13 and moto g10 power android 11)

can u pls provide any reference ?

**Comment by eraytech** [comment]
verified and working, regarding checkbox, its already available in other ticket

**Comment by eraytech** [comment]
![WhatsApp Image 2024-09-24 at 17 37 28_7d7f8f44](https://github.com/user-attachments/assets/771713d6-53f2-4e87-b762-a8cf000e8c5a)
