### ISSUE TITLE
[Web][Staffing Consultancy] Posted jobs are not showing in 'Company Details' page under "Jobs' tab

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#376]
1. Login as SC
2. Go to Staffing Consultancy -> Company Profile -> Jobs (tab)
3. Observe if any posted jobs are showing in this tab

Actual result:
Posted jobs by this SC is not showing 

Expected result: 
Shall show all jobs posted by this SC under [Post a bob] banner
Show same tile as in 'Posted Jobs"

![image](https://user-images.githubusercontent.com/101229315/235503468-20041927-e69e-4816-b243-cb0ecb44fa52.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
working, verified
