### ISSUE TITLE
[Web][Staffing Consultancy] Unable to edit "Posted jobs"

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#377]
1. Login as SC/Employer
2. Post a Job
3. Try to edit posted job

Actual result:
No option to edit posted job.

Expected result:
SC or Employer shall be able to edit posted job.

![image](https://user-images.githubusercontent.com/101229315/235503884-37ad4e3d-d7a1-437a-bb8e-54b4fa1731e5.png)

**Comment by Abhinavgunda25** [comment]
issue solved., please check

**Comment by eraytech** [comment]
Verified and closed
