### ISSUE TITLE
[Android 1.9] Pricing details are not showing in payment summary page

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#379]
1. Login as SC
2. More->Subscriptions->Click on any [Subscribe]

Actual result:
Blank details are showing for pricing

Expected:
Shall show plan price details like before. Earlier version was working fine.

![image](https://user-images.githubusercontent.com/101229315/236104491-be228861-4268-497d-b414-6f0e60abb41a.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
please check
[379.webm](https://github.com/gak112/DearJobTesting/assets/49630766/9d2d6f33-0d48-4357-ab8d-25e6fcba6efb)

**Comment by eraytech** [comment]
verified
