### ISSUE TITLE
[Android 1.9] Contact us page is not reflecting data from admin page (social icons, address, email)

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#380]
1. Install Android 1.9
2. Login as SC
3. Go to More->Contact us

Actual result:
Social links not working.
Address not showing from admin page
Email id not showing correctly from admin page

Expected:
All social links shall work
Office address shall show correctly 
Email id shall show correctly, same as entered in admin page.

![image](https://user-images.githubusercontent.com/101229315/236106908-eb9166a1-5e46-467e-9fff-b25222253473.png)

Admin page:
![image](https://user-images.githubusercontent.com/101229315/236106728-000825dc-f6fd-4e4e-a33f-56ca33ebb997.png)

![image](https://user-images.githubusercontent.com/101229315/236106749-3be310ca-c916-4ebb-9d93-ea2b522c57dd.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
working, verified
