### ISSUE TITLE
[Android 1.9] In Contact us page: Error shows 'Email is required' although email id is entered

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#381]
1. Install Android 1.9
2. Login as SC
3. Go to More->Contact us
4. Fill all details in form and try to send email.

Actual result:
Although email id is entered, error displays "Email is required"

Expected result:
Should be able to send email

![image](https://user-images.githubusercontent.com/101229315/236107311-4e93f05c-35a3-40d5-ab0e-20c86fbf318b.png)

**Comment by Abhinavgunda25** [comment]
issu resolved.,

**Comment by eraytech** [comment]
Verified and closed in 2.3
