### ISSUE TITLE
[Android 1.9] Unable to create distribution list, submit button struck

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#382]
1. Install Android 1.9
2. Login as SC
3. Go to More->Distribution List->Click on 'Create distribution list' icon at bottom right of the page.
4. Enter any name and click [Submit]

Expected:
Shall create new distribution list name

Actual:
Submit button changed to [...] and struck. New DL name not created.

![image](https://user-images.githubusercontent.com/101229315/236108100-8da79005-03d5-4d61-8904-7fc2de8452c2.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
please check
[382.webm](https://github.com/gak112/DearJobTesting/assets/49630766/704c2b7d-69ec-4a7c-b8f1-c879d58f664d)

**Comment by eraytech** [comment]
Verified and closed
