### ISSUE TITLE
[Android 1.9/IOS] Unable to add single email id to distribution list

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#384]
1. Install Android 1.9/IOS
2. Login as SC
3. Go to More->Distribution List
4. All distribution lists are shown. Click on [View] icon on any DL
5. All emails ids are shown. Click on [Add] icon at bottom right of page
6. 'Add mass email list' page displayed. 
7. Select 'Add Single' and enter all details and [Submit]

Expected result:
Shall add email id to DL.
Change "Do want to" -> "Do you want to"

Actual:
Nothing happens after clicking [Submit]

![image](https://user-images.githubusercontent.com/101229315/236109544-7652e5f4-13d5-4c99-bb8d-87386720d593.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
please check
[384.webm](https://github.com/gak112/DearJobTesting/assets/49630766/32ecdb41-ab43-4501-bce5-6803f9514445)

**Comment by eraytech** [comment]
Verified and closed
