### ISSUE TITLE
[Web][Job Seeker details] email ID and mobile number are overlapping with each other when viewing 'Edit Profile'

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#387]
Steps:

1. Open the Website https://dearjob.org
2. Create a profile in job seeker.
3. Click on 'Job Seeker' menu tab.
4. Click on 'edit profile'

Actual Result:
email ID and mobile number are overlapping with each other.

Expected Result:
email ID and mobile number should be clearly visible and should not overlap with each other.

![Screenshot3 in Jobseeker Details](https://user-images.githubusercontent.com/101229315/236398457-cedb1d6f-e3b7-499a-b1ab-140727733f70.png)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Working fine.
