### ISSUE TITLE
[Web][Employer Registrations] The 'submit' button does not redirect to another page and is not visible even after the correction has been made

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#388]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' menu tab.
3. Click on 'Employer' area.
4. Fill employer details by leaving any field in 'Employer Registration' form.(If user forget to enter any details)
5. Click on the 'submit' button.
6. Error is displayed.
7. Again fill the missing field.

Actual Result:
Even after the correction is done, Clicking on the 'submit' button does not redirect to another page, and the button itself is not visible (Blank)

Expected Result:
Even after the correction is done, Clicking on the 'submit' button should redirect to another page, and the button itself should be visible (Should not be blank)

![Screenshot5 in employer registration](https://user-images.githubusercontent.com/101229315/236443951-50ea25f0-5a47-48f2-b24c-16862a3bd5a2.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
working fine.
