### ISSUE TITLE
[Web][Job Seeker registration]Even when no details are entered in the Skillset form, it still gets added when the 'Add' button is clicked.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#391]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' in menu Tab
3. Click on 'Job Seeker' area.
4. In Skillset, without giving any details, click on 'add' button

Actual Result:
Even when no details are entered in the Skillset form, empty fields are getting added when the 'Add' button is clicked.

Expected Result:
Empty fields should not be added when no details are entered in the Skillset.

![Screenshot8 jobseeker registration-SkillSet](https://user-images.githubusercontent.com/101229315/236619767-3d04366c-bab0-4a1b-bcdf-8a3719040cfb.png)

**Comment by eraytech** [comment]
Enable [Add] button only after entering all details

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
please check
[391.webm](https://github.com/gak112/DearJobTesting/assets/49630766/9901b646-79a2-4b7e-b5e2-d36d5bdc0683)

**Comment by eraytech** [comment]
not resolved, jobseeker registration page not working, kindly check

**Comment by eraytech** [comment]
it does not allow further progress if the experience is only in months. Conversely, for years, it expects months to be entered to proceed.

**Comment by eraytech** [comment]
![Screenshot 2023-05-28 231659](https://github.com/gak112/DearJobTesting/assets/101229315/eef0b043-d591-4c33-9a70-7273eab08439)

**Comment by eraytech** [comment]
Make minimum 3 skills to add as mandatory. Allow 'Save & Next" only when atleast 3 skills are added.

**Comment by eraytech** [comment]
Raised separate issues: 
https://github.com/gak112/DearJobTesting/issues/553
https://github.com/gak112/DearJobTesting/issues/412
