### ISSUE TITLE
[Web] [Staffing Consultancy] Employer subscription plans shows in SC 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#401]
1. Login as SC
2. Menu=>SC=>Company Profile -> Click on [Go to Plans] button
![image](https://user-images.githubusercontent.com/101229315/236712087-f15265ee-250e-450a-9a9f-366760f40549.png)
3. Observe the plans showed here

Actual result:
Employer subscription plans are showing

Expected:
Shall show SC subscription plans

![image](https://user-images.githubusercontent.com/101229315/236712255-12b4c04f-a757-4227-bf54-f93be47dd95d.png)

![image](https://user-images.githubusercontent.com/101229315/236712270-9df0336b-bfc3-4df5-b8b6-da437823371c.png)

![image](https://user-images.githubusercontent.com/101229315/236712280-f6a03fee-a28c-4f5a-a4f5-1e37a22f15cf.png)

**Comment by Abhinavgunda25** [comment]
Please check
[401.webm](https://github.com/gak112/DearJobTesting/assets/49630766/b19369b4-3e97-4ade-a05d-91001d3cb7d7)

**Comment by eraytech** [comment]
resolved
