### ISSUE TITLE
[Web][Job Seeker registration]Content error exists, where different names are used in the validation message (Education Type) compared to the actual field(Course Type).

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#405]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' in menu Tab
3. Click on 'JobSeeker' area.
4. In 'Education details', fill all details except 'Course type'
5. Click on 'Save & Next'

Actual Result:
A validation error message appeared stating, "Please select Education Type."

Expected Result:
The validation error should appear as "Please select Course Type" instead of "Please select Education Type."

![Screenshot18 Jobseeker-content error for coursetype](https://user-images.githubusercontent.com/101229315/236766041-fe341f1d-b8da-485a-b093-8a03359fa512.png)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified
