### ISSUE TITLE
[Web][Job Seeker registration]In Skillset, months field allows durations greater than 11 months and there is no clear differentiation between durations entered in years and months in the display.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#412]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' in menu Tab
3. Click on 'JobSeeker' area.
4. Enter years and months in the skillset field

Actual Result:
In Skillset, months field allows durations greater than 11 months and there is no clear differentiation between durations entered in years and months in the display.

Expected Result:
The months edit box should not allow values greater than 11, indicating that only values up to 11 months are acceptable. Additionally, in the displayed skills section, the experience should be clearly mentioned as either months or years to provide clarity on the duration.

Enhancement:
It would be beneficial, if there is drop down for selecting number of months ranging from 1 to 11. 

https://user-images.githubusercontent.com/101229315/237015000-8620c8dc-2081-49f7-92ec-7a8c55599a81.mp4

**Comment by Abhinavgunda25** [comment]
issue Resolved., In Experience Months number should in between 0 to 11

**Comment by eraytech** [comment]
All fields are mandatory here:
Enable [Add] Button only when all 4 details are filled.
Skill set: Show drop down from master table. If new skill is added, update it to master table.

Enable [Save & Next] only when **minimum 3 skills** are added.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/ed9eadae-7352-400e-8f06-de5a0c431ff7)

**Comment by eraytech** [comment]
Add a note on top of skillset table: 
"Note: Add as many skills as possible, but minimum 3 are needed to proceed further. Job alerts, profile match works better if more skills are added "

![image](https://github.com/gak112/DearJobTesting/assets/101229315/fbe07ebd-5de0-443a-9b39-344d9ef86aac)

**Comment by eraytech** [comment]
Add a note on top of skillset table:
"Note: Add as many skills as possible, but minimum 3 are needed to proceed further. Job alerts, profile match works better if more skills are added "

kindly add the total note

**Comment by eraytech** [comment]
verified
