### ISSUE TITLE
[Web][Job Seeker Registration] Preferred Work Location field should be mandatory in 'Employment Details'.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#419]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' in menu Tab
3. Click on 'Job Seeker' area.
4. In the 'Employment details', Select Job Location type as, on-Site or Hybrid

Actual Result:
It's allowing to register even when 'Preferred work location' is not entered.

Expected Result:
The Preferred Work Location field should be marked as mandatory, meaning that users must provide a selection for this field before proceeding.

https://github.com/gak112/DearJobTesting/assets/101229315/d03383b4-a7ef-4c87-acdf-73ceb54d710f

**Comment by Abhinavgunda25** [comment]
issue Resolved

**Comment by eraytech** [comment]
working fine,verified
