### ISSUE TITLE
[Web][Job Seeker]In 'Basic Details', label name should be 'Expected Salary' instead of 'Salary' 

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#420]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'Register' in menu Tab
3. Click on 'Job Seeker' area.
4. After registration, click on 'Job Seeker' dropdown.
5. Click edit for 'Basic details' in edit profile.

Actual Result:
Label name is available as 'Salary'

Expected Result:
It would be beneficial to label the field as 'Expected Salary' instead of 'Salary' to avoid confusion to users whether they need to give 'Current Salary' or 'Expected Salary'

![Screenshot25 JobSeeker-Expected Salary](https://github.com/gak112/DearJobTesting/assets/101229315/1772f4c3-1317-4ee3-b004-c3d6d209154a)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
verified
