### ISSUE TITLE
[Web][Staffing Consultancy]'Submit' button is not functioning in 'Market Job' page.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#426]
Steps:
1. Open the Website https://dearjob.org
2. Click on 'register'
3. Click on 'Staffing Consultancy'.
4. After registration, enter the fields in the 'Market Job'.

Actual Result:
Non functionality of the 'Submit' button.

Expected Result:
'Submit' button should work as per functionality.

![Screenshot28 SC-Non functioning of Submit button](https://github.com/gak112/DearJobTesting/assets/101229315/ada1919a-cb4e-4bdf-9556-9a2e9e304cdf)

**Comment by Abhinavgunda25** [comment]
market job changed to post job

**Comment by eraytech** [comment]
working, verified
