### ISSUE TITLE
[Web][Job Seeker-My Resumes] The 'Submit' button is missing in the 'Add resume' section, and the file uploading process is taking an indefinite amount of time.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#431]
Steps:
1. Open the Website https://dearjob.org.
2. Login to Job Seeker.
3. Go to 'My resume' in Basic details of 'Job Seeker' dropdown.

Actual Result:
'Submit' button is missing for submitting the resume and the file uploading process is taking an indefinite amount of time..

Expected result:
'Submit' button should be visible and the file uploading process time should be optimized.

![Screenshot33-Submit button missing in add resume](https://github.com/gak112/DearJobTesting/assets/101229315/22c9a7c5-626f-44df-90fb-fc527a62bd3a)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by Abhinavgunda25** [comment]
please check
[431.webm](https://github.com/gak112/DearJobTesting/assets/49630766/9a297f9d-ae83-41ae-b569-51d4ef27cda3)

**Comment by eraytech** [comment]
submit option is available, but it is not submitting any resume after all positive inputs

**Comment by eraytech** [comment]
Submit button is available, but it is not working as per functionality. Not able to Submit the added resume. Kindly check.

https://github.com/gak112/DearJobTesting/assets/101229315/6b87570f-0e38-4db1-995d-f6c6a5bf4d43

**Comment by eraytech** [comment]
Verified and able to submit the resume.
