### ISSUE TITLE
[Web][Job Seeker-Add Resumes]The 'submit' button neither redirect to another page nor closing and the button is not visible when tried to upload second resume.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#432]
Steps:
1. Open the Website https://dearjob.org.
2. Login to Job Seeker.
3. In add resume of upload resume section, in Basic details of 'Job Seeker' dropdown, add the resume.

Actual Result:
After clicking the submit button on uploading the file, it is neither closing directly nor highlighting any closing button and after uploading the second resume, the button itself is not visible (Blank)

Expected result:
After the second resume upload is done, Clicking on the 'submit' button should redirect to another page, and the button itself should be visible (Should not be blank). After submitting one resume, it should automatically close, or highlight the closing buttons.

https://github.com/gak112/DearJobTesting/assets/101229315/0c481a25-f10e-4cd4-957b-782aff051f59

![Screenshot34- add resume error](https://github.com/gak112/DearJobTesting/assets/101229315/fe4583bf-a894-473c-b73b-5ab62c5d9f12)

**Comment by Abhinavgunda25** [comment]
issue resolved., please check

**Comment by Abhinavgunda25** [comment]
please check
[432.webm](https://github.com/gak112/DearJobTesting/assets/49630766/e23f4491-2d5c-4c56-911b-c23c6f75c295)

**Comment by eraytech** [comment]
issue not resolved, kindly check

**Comment by eraytech** [comment]
Hi Abhinav, I see its working fine in localhost. Is it pushed to live?

**Comment by eraytech** [comment]
The 'Submit' button is not functioning to check it further. Kindly check.

https://github.com/gak112/DearJobTesting/assets/101229315/2a3c0130-0627-439f-aeb2-53a49da33597

**Comment by eraytech** [comment]
Issue closed.

But new skills added during adding resume is not updated to master skills table.

**Comment by eraytech** [comment]
Verified.
