### ISSUE TITLE
[Web][Job Seeker-Add resume] The 'add resume' section is allowing saving without uploading the file.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#440]
Steps:
1. Open the Website https://dearjob.org
2. Login to Job Seeker.
3. Click on 'Edit Profile' in Job Seeker dropdown.
4. Move to 'Add resume' in the 'Upload Resume' section.
5. Give the title and click on 'submit' button.

Actual Result:
A information message appeared, as 'resumes saved-saved successfully'

Expected Result:
The resume shouldn't save immediately without uploading the file. Uploading the file should be mandatory.

https://github.com/gak112/DearJobTesting/assets/101229315/dc7b945f-80fe-47f4-b115-03adc0e57e77

**Comment by Abhinavgunda25** [comment]
Issue resolved., Please check
[screen-capture.webm](https://github.com/gak112/DearJobTesting/assets/49630766/9dc907b7-332e-44b3-afb2-30c94f972c59)

**Comment by eraytech** [comment]
the upload file format is doc ,but in display it showing as pdf file , kindly clarify

if user uploads in particular format , it should reflect same format

**Comment by eraytech** [comment]
if user uploads in particular format , it should reflect same format.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/e3f625cc-f64e-43c1-820c-ad4f911a5ac6)


![image](https://github.com/gak112/DearJobTesting/assets/101229315/05fbea27-dca7-4907-8579-3fc24479c5f7)

**Comment by eraytech** [comment]
verified and working in web and andriod 3.8v
