### ISSUE TITLE
[Web][Staffing consultancy] After Entering details into mandatory fields, it is not clicking submit button.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#441]
1. Open the website htts://dearjob.org
2. Click on Staffing consultancy
3. Login to Staffing consultancy with all positive values.
4. Page of the Market job given all values and also not submitting the application.
5. And not at all throwing any kind of error in that page.
 
![Screenshot (7)](https://github.com/gak112/DearJobTesting/assets/101229315/bdebd533-8b9f-4e32-bc67-755170363808)

Actual Result: 
It is not throwing any error while submitting and not taking to next page.
Expected Result:
It should throw an error like please fill all fields or some error message.

**Comment by Abhinavgunda25** [comment]
Market job is changed to post a job

**Comment by eraytech** [comment]
working ,verified
