### ISSUE TITLE
[Web][All-Change password]Absence of eye icon in 'change Password' section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#446]
Steps:
1. Open the Website https://dearjob.org
2. Register as Job Seeker/ Employer/ Staffing consultancy.

Actual Result:
Eye icons are not present in the 'Change Password' page of Job Seeker, Employer and Staffing consultancy.

Enhancement:
It would be beneficial if eye icon is included in the 'Change Password' page of Job Seeker, Employer and Staffing consultancy.

![Screenshot 40 -Change password eye icon visibility](https://github.com/gak112/DearJobTesting/assets/101229315/1ef6e960-2291-4f94-a6ae-b69800eed4de)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
https://github.com/gak112/DearJobTesting/assets/101229315/ef06b565-812a-4c78-b915-a7d38ba24a11

still not resolved, reflecting different page in between

**Comment by eraytech** [comment]
Verified and closed
