### ISSUE TITLE
[All][Employer/SC] Unsubscribed Jobseeker profile shows as Priority applicant

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#468]
1. Register as Jobseeker: Ex: Jennifer Lewis
2. Not subscribed as Priority 
3. Login as employer or staffing consultancy
4. Go to Profile search->Search for "Jennifer Lewis"

Actual result:
Result shall show but not yellow border and crown icon.

Expected:
Yellow border to tile and crown icon shall show only for priority applicants.

In Admin page: Jennifer is in FREE plan
![image](https://github.com/gak112/DearJobTesting/assets/101229315/33e71796-0c97-423b-bdba-df487f25749a)

In profile search result page: profile shows as priority applicant:
![image](https://github.com/gak112/DearJobTesting/assets/101229315/31f7b740-f964-44eb-a964-84b2293b49f1)

**Comment by Abhinavgunda25** [comment]
issue resolved.,

**Comment by eraytech** [comment]
Verified and working fine.
