### ISSUE TITLE
[Web] Angular image is appearing for DearJob logo in Google search

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#504]
Steps:
Searched 'DearJob' in Google search

Result:
Angular image is appearing in logo of DearJob instead of DearJob's logo.

![Screenshot52-Appearing as angular image](https://github.com/gak112/DearJobTesting/assets/101229315/d8cd19c7-5cda-4894-9fca-dcb8a5865436)

**Comment by Abhinavgunda25** [comment]
![google search dearjob](https://github.com/gak112/DearJobTesting/assets/49630766/b0922c4e-16b6-4426-b817-87045105ddb4)

**Comment by eraytech** [comment]
Verified, hence, closing the issue.
