### ISSUE TITLE
[Web/Android 2.2][All-Subscriptions] Refund from the Existing subscription (still in live) to be added to the new subscription that is about to be taken.  

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#570]
Steps:
1. Open the Android version of 2.2 or open the Website https://dearjob.org
2. Login as Employer/ Job Seeeker/ Staffing Consultancy with subscription.
3. Tap on other subscription plan

Actual Result:
Existing plan is being overwritten by the new plan that is taken, and no refund amount is given.
Eg: If a user is in Gold plan ($49.99) with still 15 days validity wants to change to Platinum plan ($149.99), the Gold plan is completely overwritten and the user is paying another $149.99 for the new plan.
 
Enhancement:
Eg: If a user is in Gold plan ($49.99) with still 15 days validity wants to change to Platinum plan ($149.99),
It would be more beneficial if we refund the remaining 15 days amount ($24.99) of Gold plan ($49.99) and the 15 days amount ($24.99) of Gold plan should automatically deduct from the Platinum plan ($149.99).
In the current scenario, the user needs to pay $125 ($149.99-$24.99)
It should appear as:
Existing plan and amount:
Remaining days:
Refund from existing plan:
New plan amount:
Amount need to be paid:

According to remaining days, the amount should be deducted.
and the same scenario shouldn't be applied if user wants to change from high plan to low plan

**Comment by gak112** [comment]
this is not bug, and it is new requirement
