### ISSUE TITLE
[Web/Android 2.4][Job Seeker] Not getting pop-up message when Email ID & Password are mismatching.

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#606]
Steps:
1. Open the Website https://dearjob.org or Open the Android version of 1.9
2. Login as Job Seeker and give incorrect password

Actual Result:
For Web: It is not displaying any pop-up message after clicking on Login button. 
For Android: pop-up displaying as, 'The Password is invalid or the user does not have a password'
 
Expected Result:
for both web and android, it would be more beneficial if call-out message appear as, 'login ID or password is mismatching' or 'Invalid details. Please check the Email Id and Password'

![Screenshot113-Wrong pop-up](https://github.com/gak112/DearJobTesting/assets/101229315/348e59dc-785b-4362-bc06-f173c566b00b)

**Comment by QSPaysys1** [comment]
pop-up displaying as, 'The Password is invalid or the user does not have a password'. It is Database server generated text, cannot change text.

**Comment by eraytech** [comment]
verified and working in both web and andriod 3.6v
