### ISSUE TITLE
 [WEB] [JS-Register-Basic Details] UI Inconsistency - Label Capitalization in Confirm Password Field

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#648]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. On the "Basic Details" section of the registration form, find the field for entering a confirm password.

**Actual Result:**
In the JobSeeker registration form, there is an inconsistency in the capitalization of labels for fields. Specifically, labels for fields like "First Name" and "Last Name" capitalize the first letter of each word, following a standard convention. However, the label for the "Confirm password" field does not follow this convention, as it is displayed as "Confirm password" with a lowercase "p" in "password."

**Expected Result:**
For consistency and improved user experience, the label for the "Confirm password" field should follow the same capitalization convention as other field labels, capitalizing the first letter of each word, resulting in "Confirm Password."

![image](https://github.com/gak112/DearJobTesting/assets/101229315/f63cff77-85ab-43ed-9d0a-1442b67fa2b2)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified
