### ISSUE TITLE
[WEB] [JS-Register-Basic Details] Data Loss in Current Location Field

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#649]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. On the "Basic Details" section of the registration form, find the field for entering a current location.

**Actual Result:**
While entering data in the "Current Location" field, the page auto-populates location suggestions. When a location is selected, it gets saved below the "Current Location" field. However, after clicking the "Save and Next" button and then returning to the same page, the selected location is visible below the field but has become empty within the "Current Location" field itself.

**Expected Result:**
The selected location should remain populated in the "Current Location" field, both below the field and within the field itself, even when navigating back to the same page. This ensures data consistency and a better user experience.

https://github.com/gak112/DearJobTesting/assets/101229315/8fda2064-31f7-4cde-aa1d-f64553fa88d7

**Comment by QSPaysys1** [comment]
It is impossible., it is autocomplete input

**Comment by eraytech** [comment]
Closing
