### ISSUE TITLE
[WEB] [JS-Register-Education Details]Duplicate Course Entries in Dropdown

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#650]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details" section and move to the "Education Details" section.
5. On the "Education Details" section of the registration form, find the field for entering a course.

**Actual Result:**
In the "Course" field, there is a dropdown menu containing a list of available courses. If a course is not available in the dropdown, users can add it as a new item. However, after submitting the form, the dropdown menu may contain multiple duplicate entries for the same course. For example, "B.Tech" may appear multiple times in the dropdown menu.

**Expected Result:**
The dropdown menu for the "Course" field should not allow duplicate entries. When a user adds a new course, it should be saved as a single, unique entry in the dropdown list. This ensures that the list remains organized and free of duplicate data.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/09d44ebe-00bf-46ef-a126-bc0b8dd7384f)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
working , also verified in admin page.
