### ISSUE TITLE
[WEB] [JS-Register-Education Details] Missing Placeholder in Dropdown Menus

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#652]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details" section and proceed to the "Education Details" section.
5. On the "Education Details" section of the registration form, find the fields for entering a Course and Institute.

**Actual Result:**
In the "Education Details" section, the dropdown menus for both the "Course" and "Institute" fields do not display any placeholder text. However, users are able to select courses from the dropdown without guidance.

**Expected Result:**
The dropdown menus for the "Course" and "Institute" fields should display a placeholder text or default option, such as "Select Course" and "Select University/Institute " respectively, as a suggestion to users. This provides a clear and user-friendly experience during registration.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/a2603e08-51ed-4e7e-a9eb-04e58b68acab)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified
