### ISSUE TITLE
[WEB] [JS-Register-Skill Set] Missing Placeholder in Dropdown Menus

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#653]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details" and "Education Details" sections, and proceed to the "Skill Set" section.
5. On the "Skill Set" section of the registration form, find the fields for entering a Skill Set and Proficiency.

**Actual Result:**
In the "Skill Set" section, the dropdown menus for both the "Skill Set" and "Proficiency" fields do not display any placeholder text. Users are unable to see any default options or suggestions for selecting their skill sets or proficiency levels.

**Expected Result:**
The dropdown menus for the "Skill Set" and "Proficiency" fields should display placeholder text or default options, such as "Select Skill Set" and "Select Proficiency," respectively, to guide users in making their selections. This would enhance the user experience during registration.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/de947407-7b5d-4bf1-a63e-e93559ca0664)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
