### ISSUE TITLE
[WEB] [JS-Register-Experience Details] Placeholder Text Missing in "Availability" Fields

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#655]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details," "Education Details," "Skill Set," "Employment Details," "Work Authorization," and proceed to the "Experience Details" section.

**Actual Result:**
In the "Experience Details" section, there are dropdown menus for selecting "Availability." However, these dropdown menus do not display any placeholder text or default options to guide users in selecting their availability. While users can select an option from the dropdown, the absence of placeholder text or default options may lead to confusion.

**Expected Result:**
The "Availability" dropdown menus should display placeholder text or default options that guide users in selecting their availability. This will enhance the user experience by providing clear instructions and options for this field during registration.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/41f402f1-cef3-4fee-9ce8-e3dfa1629df1)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
