### ISSUE TITLE
[WEB] [JS-Register-Experience Details]Field Validation and Placeholder Issues in "Experience Details" Section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#657]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details," "Education Details," "Skill Set," "Employment Details," "Work Authorization," and proceed to the "Experience Details" section.
5. In the "Experience Details" section, select the "EXPERIENCED" radio button.

**Actual Result:**
In the "Experience Details" section, when selecting the "EXPERIENCED" radio button, several issues are observed:
- The "Total Experience" field has two input fields, one for the total count and the other for the type (with options like years and months). Neither of these input fields has a placeholder, making it unclear to users what each field represents.
- The "Current Job Designation" field has a placeholder, but it should be replaced with "Enter Current Job Designation" for clarity.
- The "Current Organization" field also has a placeholder, but it should be replaced with "Enter Current Organization" for clarity.
- The "Availability" field has a dropdown with data but lacks a placeholder, which could provide context to users regarding the expected input.

**Expected Result:**
1. The "Total Experience" field should have clear placeholders for both the total count and the type .
2. Placeholder text for "Current Job Designation" should be updated to "Enter Current Job Designation."
3. Placeholder text for "Current Organization" should be updated to "Enter Current Organization."
4. The "Availability" dropdown should include a placeholder  to indicate its purpose to users.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/8bc6dbf2-5731-45aa-af0d-51cb3cec82e8)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
