### ISSUE TITLE
[WEB] [JS-Register-Education Details] Issue with Reflecting New Course in Dropdown After Successful Registration

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#658]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details" section and proceed to the "Education Details" section.
5. In the "Education Details" section, find the field for entering a course.
6. Add a new course as a manual entry that is not available in the dropdown.
7. Complete the registration process by filling in all required fields and verifying the user with an OTP.

**Actual Result:**
After successful registration, the new course added as a manual entry during the registration process is not reflected in the dropdown menu of available courses for future registrations. Users are unable to select this newly added course when registering for the site.

**Expected Result:**
Upon successful registration, the new course that was added as a manual entry during the registration process should be automatically included in the dropdown menu of available courses. This allows future users to select this course when registering for the site, ensuring consistency and accuracy in course options.

entered manually during registeration is reflecting in profile
![image](https://github.com/gak112/DearJobTesting/assets/101229315/2eef99b1-0b6b-458e-b469-6d8420292478)

same not avaiable in admin master data of course :

![image](https://github.com/gak112/DearJobTesting/assets/101229315/aa4be7b5-1e19-4517-beb4-e47e84cac9eb)

adding video refernce of registeration

https://github.com/gak112/DearJobTesting/assets/101229315/b2d6019b-bd90-4b9e-bf6a-f77998657405

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
