### ISSUE TITLE
 [WEB] [JS-Register-Education Details] Issue with Reflecting New Institute/University in Dropdown After Successful Registration

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#659]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "Register" link in the menu tab.
3. From the available registration options, choose "JobSeeker."
4. Fill in the required details in the "Basic Details" section and proceed to the "Education Details" section.
5. In the "Education Details" section, find the field for entering an institute or university.
6. Add a new institute or university as a manual entry that is not available in the dropdown.
7. Complete the registration process by filling in all required fields and verifying the user with an OTP.

**Actual Result:**
After successful registration, the new institute or university added as a manual entry during the registration process is not reflected in the dropdown menu of available institutes/universities for future registrations. Users are unable to select this newly added institute or university when registering for the site.

**Expected Result:**
Upon successful registration, the new institute or university that was added as a manual entry during the registration process should be automatically included in the dropdown menu of available institutes/universities. This allows future users to select this institute or university when registering for the site, ensuring consistency and accuracy in institute/university options.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/bc31fc07-5df3-4af9-82dd-e3b792dc5771)

![image](https://github.com/gak112/DearJobTesting/assets/101229315/6fd541e1-8e1b-4745-b98b-c652e59c9717)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working
