### ISSUE TITLE
[WEB] [JS-Edit Profile-Basic Details ]Discrepancy in Displayed Phone Number in Profile Edit Section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#660]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "LOGIN" link in the menu tab.
3. Enter the registered JobSeeker email ID and password, then click on the login button or press enter.
4. After successful login, click on "Job Seeker" in the menu tab and select "Edit Profile."
5. Verify whether all details captured during registration are available in the profile.
6. Click on the "Basic Details" section.

**Actual Result:**
The phone number is visible in the "Basic Details" section in the profile view. However, when clicking on the "Edit" button for the "Basic Details" section, the mobile number field appears to be empty.

**Expected Result:**
When clicking on the "Edit" button for the "Basic Details" section, the mobile number field should display the phone number that was previously entered during registration. The displayed phone number in the "Edit" mode should match the phone number visible in the profile view.

https://github.com/gak112/DearJobTesting/assets/101229315/a26a2fbc-b2b9-4e78-a6c4-5524a6151c1d

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working fine
