### ISSUE TITLE
[WEB] [JS-Edit Profile-Personal Details]Incorrect Display of "Prefer Not to Say" in Personal Details Section

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#661]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "LOGIN" link in the menu tab.
3. Enter the registered JobSeeker email ID and password, then click on the login button or press enter.
4. After successful login, click "Job Seeker" in the menu tab and select "Edit Profile."
5. Verify whether all details captured during registration are available in the profile.
6. Click on the "Personal Details" section.

**Actual Result:**
In the "Personal Details" section, the option "Prefer Not to Say" is displayed as "PREFERNOTTOSAY" instead of "Prefer Not To Say."

**Expected Result:**
The option "Prefer Not to Say" should be displayed correctly as "Prefer Not to Say" in the "Personal Details" section. The formatting should be appropriate and in line with the user's selection.

![image](https://github.com/gak112/DearJobTesting/assets/101229315/279cf5ec-b208-45ab-a7e6-1e20a36f6c7e)

**Comment by QSPaysys1** [comment]
issue resolved., please check

**Comment by eraytech** [comment]
verified and working.
