### ISSUE TITLE
[WEB] [Employer-Edit Profile] Placeholder for "About Company" Section in Employer Profile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#694]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "LOGIN" link in the menu tab.
3. Enter the Employer's registered Email ID and Password and click on the login button or press Enter on the keyboard.
4. After successful login, click "Employer" in the menu tab and select edit profile.
5. Click on the "About Company" section.

**Actual Result:**
The "About Company" section has a text area with a placeholder displaying "enter here".

**Expected Result:**
The "About Company" section should provide a text area with a placeholder guiding the user to input a brief description of their company and its mission. Suggested placeholder: "Briefly describe your Company "

![image](https://github.com/gak112/DearJobTesting/assets/101229315/d499501c-336a-414a-a989-f59abe62a26d)

**Comment by QSPaysys1** [comment]
In Company Editor JS we cannot use placeholders
