### ISSUE TITLE
[WEB] [Employer-Edit Profile]  Placeholder for "Our Mission" Section in Employer Profile

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#695]
**Steps:**
1. Open a web browser and navigate to the website: "https://dearjob.org".
2. On the website's homepage, locate and click on the "LOGIN" link in the menu tab.
3. Enter the Employer's registered Email ID and Password and click on the login button or press Enter on the keyboard.
4. After successful login, click "Employer" in the menu tab and select edit profile.
5. Click on the "Our Mission" section.

**Actual Result:**
The "Our Mission" section has a text area with a placeholder displaying "enter here".

**Expected Result:**
The "Our Mission" section should provide a text area with a placeholder guiding the user to input their company's mission statement. Suggested placeholder: "Enter your company's mission statement..."

![image](https://github.com/gak112/DearJobTesting/assets/101229315/36f5ca0d-5b6b-4848-9c47-fdedc6075f7a)

**Comment by QSPaysys1** [comment]
It is not possible for placeholder in Editor Js

**Comment by eraytech** [comment]
changes satisfies the requirement
