### ISSUE TITLE
Job Seeker --> Search Details --> Job Details

### ISSUE THREAD

**Issue by rukku3** [gak112/DearJobTesting#70]
- Replace "Get job updates" with paid promotions(ADs) or "Priority Applicant" details
- 2 types of job postings : directly on dearjob and pulled from APIs. 
- pulled from APIs: when clicked on "apply" should redirect to their website
- Posted directly on DearJob: when clicked on 'apply", should redirect to a page with fields such as "Select resume",  "Select cover letter', etc
- refer to original admin panel --> import jobs
-

**Comment by srinuheroictechno** [comment]
completed
