### ISSUE TITLE
[Android] Splash screen did not display when app opened

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#94]

**Comment by Abhinavgunda25** [comment]
Issue Resolved., Please check now it is showing "d" icon

**Comment by Abhinavgunda25** [comment]
![WhatsApp Image 2023-05-05 at 10 23 06 AM](https://user-images.githubusercontent.com/49630766/236380107-62d7060e-d3c4-42e6-b7ff-d27f9eccc67f.jpeg)
splash screen added

**Comment by eraytech** [comment]
verified
