### ISSUE TITLE
Web -> Login -> forgot pwd : further instructions

### ISSUE THREAD

**Issue by eraytech** [gak112/DearJobTesting#97]
1. Goto Login Screen
2. Click Forgot Password
3. Enter some email ID & click submit

Actual result:
As there is no response, Not knowing what happened after clicking.

Sugggested result:
It would be good if there are some messages/instructions that needs to be followed further

**Comment by eraytech** [comment]
Retried above scenario of 'Forgot password' functionality for an employer who is already registered and this doens't work. Expected an email alert to reset password

**Comment by Abhinavgunda25** [comment]
issue Resolved., Please check

**Comment by eraytech** [comment]
Working fine, When the "Forgot password" option is selected, an email is sent to the user.
